### ISSUE TITLE
Missing Accept-Range header resulting in videos not playable  in Safari (desktop/iOS)

### ISSUE THREAD

**Issue by tkjaergaard** [umbraco/Umbraco.Cloud.Issues#504] opened 2021-12-02 12:57 UTC
### Issue description

We have experienced on solutions migrated to the new platform that videos suddenly won't play in Safari (both desktop and iOS). It seems to be because of a missing Accept-Range header.

From what i know (and can see) of the new setup, Cloudflare is now in front of Umbraco. I've looked into it and found that it an issue known to be caused by Cloudflare (https://community.cloudflare.com/t/missing-in-header-accept-ranges-bytes/136881).

So my guess is that it might be related?

From what all is, videos ain't working. The major issue here is that it's not working in iOS, where a lot of traffic is coming from.

You can see example in Safari of it not working on [roskilde-festival.com](https://www.roskilde-festival.dk/en/).

**Comment by tkjaergaard** [comment] 2021-12-02 13:02
I can see that the suggested solution is to bypass the video extensions.

https://community.cloudflare.com/t/mp4-wont-load-in-safari-using-cloudflare/10587/24

Not sure if or how this would work

**Comment by RyuLindow** [comment] 2021-12-02 13:08
Hey @tkjaergaard 

We're aware and have reached out to Cloudflare about it :)

Currently, we're investigating it on our end.

**Comment by tkjaergaard** [comment] 2021-12-03 08:47
@RyuLindow Cool. Are you going to keep this issue updated? Or where to track progress on this?

**Comment by greystate** [comment] 2021-12-03 09:26
We have several sites with this problem too - only just found enough information to log an issue, but glad to find there's one already!

👀

**Comment by RyuLindow** [comment] 2021-12-03 09:27
We'll keep you posted here :)

**Comment by greystate** [comment] 2021-12-09 13:54
I asked this on the Umbraco Discord about a week ago but haven't got any answers yet:

> Are we able to bypass this with an IIS Rewrite rule or something? It's driving some clients up the wall that their precious videos are not playing :)

Is there really nothing we can do?

**Comment by greystate** [comment] 2021-12-16 11:04
At the risk of repeating myself: Do we (our Support, even) have *any* possible way to override this and issue a fix?

**Comment by HamDerAndrew** [comment] 2022-01-03 08:54
A little update from our end in Umbraco Support 📓 

We're trying to reproduce the issue on both AzurePack and Azure App service, but with no luck so far.
It's been tested on both v8 and v9 projects (latest versions).

To get this issue resolved faster we would love it if you, who experience it, can provide a link to the mp4 file/s that fail to play 😃 

We totally understand if you cannot refer to the files here and if you wish to discuss it more privately then feel free to reach out to us in support.
You can get a hold of us on either support@umbraco.com or in our live chat, which can be found in the bottom right corner on www.umbraco.com

**Comment by greystate** [comment] 2022-01-03 09:58
@HamDerAndrew I've sent an email on support@umbraco.com with links to a couple of files 👍

**Comment by gustaflevin** [comment] 2022-01-13 10:32
I'm having a similar issue. 
I cannot view video on Safari or on iOS. I'm on Umbraco 8.11.1.
I've tried through video tag with url and just with url, no luck.

**Comment by greystate** [comment] 2022-01-19 09:55
Has anyone found a workaround for this? E.g. would it be possible to add a Rewrite on the server to change the response code?

**Comment by tkjaergaard** [comment] 2022-01-31 19:22
@HamDerAndrew This is an example of a video not working on a LIVE Umbraco Cloud project.

Example of video not working:
https://implementconsultinggroup.com/media/8203/im-strategy-film-hero-snippet-3.mp4

Same video proxied through IMGIX:
https://implement.imgix.net/media/8203/im-strategy-film-hero-snippet-3.mp4

**Comment by greystate** [comment] 2022-02-01 09:57
@tkjaergaard Are your problem sites all on Umbraco 7? (Mine are and I'm beginning to suspect that's part of the problem...)

**Comment by HamDerAndrew** [comment] 2022-02-09 12:18
Thanks for this @tkjaergaard 🙏

@greystate has a good point here. Is it a version 7 site that this is happening on?

I ran some tests again last week in cooperation with some of our devs, but I am still not able to reproduce it.
A common denominator for the cases we have so far is that it happens on sites that are built in Umbraco 7 🤔

**Comment by tkjaergaard** [comment] 2022-02-09 12:34
> @tkjaergaard Are your problem sites all on Umbraco 7? (Mine are and I'm beginning to suspect that's part of the problem...)

Yes, all are Umbraco 7. Havn't tested on Umbraco 8/9 since we're using CDN (vimeo, imgix etc.) primarily on newer sites. 🙂

**Comment by gustaflevin** [comment] 2022-02-10 09:37
I'm on version 8.11 and my colleague is also working on version 8.x.
We are both on the new infrastructure aswell.

**Comment by meyntony** [comment] 2022-02-16 10:58
![image](https://user-images.githubusercontent.com/85172999/154250059-224ab917-e70c-4ae9-a817-2033a66a233b.png)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges
The above message was from Cloudflare after they took a look at some of the samples, we will discuss this internally and see if it fixes the issue.

**Comment by HamDerAndrew** [comment] 2022-03-08 15:14
Hey folks! 👋 

A little update on the investigation on our end.

We have managed to resolve the issue on Umbraco 8 and above.

By upgrading Umbraco Cloud's Azure Blobstorage to version 3.0.6, you should be able to fix the issue.
Nuget package is available here:
https://www.nuget.org/packages/Umbraco.Cloud.StorageProviders.AzureBlob/ 

The investigation is still ongoing for version 7 projects.

As always, if you find out anything on your end you are welcome to let us know here! 😃

**Comment by mclausen** [comment] 2024-07-16 12:45
Howdy there folks,
I can see that a lot of water has been flowing under the bridge since this issue was last answered. From what I can read a fix was presented. 

I am assuming that since there have been no updates on the matter and Umbraco 7 is out of support I will close this issue 🤞.

Feel free to reopen, if the issue persists.

 Kind regards
@mclausen - Cloud Platform/Core Teamlead

**Closed by mclausen** 2024-07-16 12:45 UTC
