### ISSUE TITLE
Views and partials not transferred from repository to live/wwwroot

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#457] opened 2021-09-30 06:46 UTC
### Issue description

I am migrating a project from Umbraco v8 to v9 and almost got it working.
I have deployed revisions which are extracted on live/remote environment on Umbraco 9.

I have also deployed existing template views and partials to remote environment, which end up just fine in `/site/repositiory` when looking in Kudo. The templates are also moved to `/site/wwwroot`, but these are empty and the partials are not transferred.

![image](https://user-images.githubusercontent.com/2919859/135401156-d47c7939-1fb0-47bd-bd28-0dc482013d38.png)

## /site/repository

![image](https://user-images.githubusercontent.com/2919859/135401049-16a6d605-f0da-457e-aac9-495029227ba6.png)

![image](https://user-images.githubusercontent.com/2919859/135401074-99b27278-5f00-4886-b0f4-182adac1cddd.png)

## /site/wwwroot

![image](https://user-images.githubusercontent.com/2919859/135401276-622ef198-bc00-4f08-a414-56094ee94dcc.png)

![image](https://user-images.githubusercontent.com/2919859/135401309-b572baf8-9cd0-4265-9744-11f06c8ecf9b.png)

So it looks like this in backoffice:

![image](https://user-images.githubusercontent.com/2919859/135400777-6a1c7c14-5a1d-4f55-a033-06057e251fc0.png)

**Comment by sitereactor** [comment] 2021-09-30 07:44
You have cut off the most interesting part of the screenshots 😅 .... can you post two things to help me check what is going on
1. The location of the Views/Partials folder(s) in the git repository (from the root of the repository folder)
2. The content of your csproj file (UmbracoProject.csproj if you haven't renamed it)

**Comment by sitereactor** [comment] 2021-09-30 07:57
FWIW I have a structure like this (locally) and it copies all the files under Views (recursive) to the `/site/wwwroot/Views` folder

![image](https://user-images.githubusercontent.com/1398823/135411110-3289a0fe-cc0d-4688-8b65-deb772094547.png)

**Repository**
![image](https://user-images.githubusercontent.com/1398823/135411404-1fef24a8-707e-4c66-9cef-8ffa6e54bfbc.png)

**wwwroot**
![image](https://user-images.githubusercontent.com/1398823/135411167-c77f20bd-589d-4604-ba4a-2b2a09e51f77.png)

**Comment by bjarnef** [comment] 2021-09-30 08:09
@sitereactor the location of Views/Partials folders in Kudo is this:

**Repository**

![image](https://user-images.githubusercontent.com/2919859/135412896-8362919a-ea5b-43c9-965d-5b4ad1cbbde4.png)

**wwwroot**

![image](https://user-images.githubusercontent.com/2919859/135413117-9680d76f-2b6b-40a7-8bfe-40a2e472bd59.png)

The project structure locally is like this:

![image](https://user-images.githubusercontent.com/2919859/135413402-88781dd5-9821-4c18-af78-2d49cb88e521.png)

**Comment by bjarnef** [comment] 2021-09-30 09:50
@sitereactor okay, so I just changed this part in UmbracoProject.csproj so `RazorCompileOnPublish` now is `false` which it is by default.

```
<!-- Set this to true if ModelsBuilder mode is not InMemoryAuto-->
<PropertyGroup>
     <RazorCompileOnBuild>true</RazorCompileOnBuild>
     <RazorCompileOnPublish>true</RazorCompileOnPublish>
</PropertyGroup>
```

I deployed this change and now the template views and partial views are copied to `/site/wwwroot/Views` folder.
Is that expected?

I guess only `RazorCompileOnBuild` should be set to `true` when not using `InMemoryAuto` ModelsBuilder mode. Not `RazorCompileOnPublish`.

**Comment by sussexrick** [comment] 2021-09-30 12:03
@bjarnef @sitereactor This is a duplicate of my issue #455. Pasting that here as this one got the attention:

On the v9 launch event one of the speakers said view compilation is disabled by default, but you recommend enabling it for production, so I went looking...

In the default csproj file you get with a v9 project on Cloud you get this:

```xml
  <!-- Set this to true if ModelsBuilder mode is not InMemoryAuto-->
    <PropertyGroup>
        <RazorCompileOnBuild>false</RazorCompileOnBuild>
        <RazorCompileOnPublish>false</RazorCompileOnPublish>
    </PropertyGroup>
```

I don't want `InMemoryAuto`, I prefer working with `SourceCodeAuto`, so I changed both values to `true` and redeployed to Cloud. Here's what I found:

* If both values are `false` you get the *.cshtml views in the `Views` folder, but you don't get `UmbracoProject.Views.dll`
* You need `<RazorCompileOnBuild>true</RazorCompileOnBuild>`, or `<RazorCompileOnPublish>true</RazorCompileOnPublish>` will fail with an error that `UmbracoProject.Views.pdb` is not found.
* If both values are `true` you get `UmbracoProject.Views.dll` but the `Views` folder has no *.cshtml files in it.

All of that makes sense from a pure ASP.NET point of view, but when you try to transfer content from your local environment to live using Umbraco Deploy, it checks that the *.cshtml files are the same in both environments. If they're missing on Cloud you get an error and Deploy doesn't work, so you can't use compiled views and the advice in the csproj file is leading to an error.

Either Deploy needs to be updated to be aware of this, or the *.cshtml files need to always be copied. The latter seems like a better solution since the check by Deploy that the files are up-to-date is a useful one.

**Comment by bjarnef** [comment] 2021-09-30 12:31
I also noticed the templates originally deployed to `/site/wwwroot/Views` was transformed to lowercase, but when I renamed the alias from `HomePage` to `homepage` and back to `HomePage` on live environment it also effect the casing of the templates.

![image](https://user-images.githubusercontent.com/2919859/135455042-d9ae82a6-817d-4427-86c8-8a2fdbd7d62b.png)

**Comment by bergmania** [comment] 2021-10-06 11:03
Looks like we need to have this in the csproj file

```
    <PropertyGroup>
        <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    </PropertyGroup>
```

**Comment by mclausen** [comment] 2024-07-16 07:17
Howdy there 🤠

Looks like a lot of water has flowed under the bridge since the last update on this issue. From what I can tell, we took a suggestion from @bergmania and added it to the template.

I’m going to assume this ticket has been solved. If not, please feel free to reopen it 👍

Kind regards,
@mclausen
Cloud Platform/Core Team

**Closed by mclausen** 2024-07-16 07:17 UTC
Labels: category/umbraco-deploy
