### ISSUE TITLE
Content Restore does not restore Url Picker Links

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco.Cloud.Issues#230] opened 2020-07-02 12:53 UTC
Hey Guys,

I am not sure, if this behaviour is intended, but in my opinion it is a bug. 

If you have a content page using Multi Url Pickers for navigation links or button links, these links are not getting restored by a content restore and need to be set manually, every time you clone and restore.

To me it does not make sense to do this step manually for instance for restoring the footer links on other environment. 

Umbraco Version 8.6.3

**Comment by nul800sebastiaan** [comment] 2020-08-18 15:11
Hi @deekoulos and apologies for the late reply. I am afraid I have bad news for you: I can't reproduce the problem. I know many people use Multi URL Picker successfully in their Cloud projects as well, so there seems to be something weird going on in your particular case. I tried picking a content node, media item and entering a manual link: 

![image](https://user-images.githubusercontent.com/304656/90530901-b4dc9680-e175-11ea-93ce-dc15a27facc4.png)

They restored to my local environment just fine.

Let us know if you have additional steps to follow in order to reproduce the problem. I'll close this for now.

**Closed by nul800sebastiaan** 2020-08-18 15:11 UTC
Labels: category/umbraco-deploy, state/needs-investigation
