### ISSUE TITLE
Data types not saved on move

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco.Cloud.Issues#300] opened 2020-12-21 11:16 UTC
When I move a document type it gets serialized immediately, so the new place can be transferred to the next server in the chain.

When I move a Data Type, it does not get serialized immediately. Because of this everything will work fine, both on the origin and on the target, until you try to deploy some content between them, then you get an error that one of the data types has an unknown dependency.

The workaround is to manually save the data type whenever you move it, but you just have to forget it one time to have this problem.

Reproduce.
1. Create a datatype
2. Deploy it
3. Move the datatype on origin
4. Deploy again
5. Datatype has not been moved on target, and content deployment no longer works

**Comment by ronaldbarendse** [comment] 2021-02-05 10:34
This is related to/a duplicate of https://github.com/umbraco/Umbraco.Cloud.Issues/issues/270 and https://github.com/umbraco/Umbraco.Cloud.Issues/issues/17.

**Comment by nul800sebastiaan** [comment] 2021-03-03 13:01
I'll close this as a duplicate of #17 indeed.

**Closed by nul800sebastiaan** 2021-03-03 13:01 UTC
Labels: category/umbraco-deploy
