### ISSUE TITLE
Usage History dashboard shows incorrect month names

### ISSUE THREAD

**Issue by lakesol** [umbraco/Umbraco.Cloud.Issues#642] opened 2023-03-30 08:11 UTC
### Issue description

The following screenshot was taken on the 30/2/2023, so the current month is March, but the previous months history shows "Mar" then "Jan", this should be "Feb", "Jan".

![image](https://user-images.githubusercontent.com/5919075/228772127-5036417b-7cc4-46cc-9b05-c641d6b4af4e.png)

**Comment by sajumb** [comment] 2023-03-30 12:36
Hi @lakesol,
Yes, you are right 😁 We noted this yesterday as well.  We have located the javascript issue and will push a fix within the next hour.

Thanks for your taking the time to report this. I will close this issue when the bug fix is out and have proved to work as intended.

**Closed** 2023-03-31 12:05 UTC
Labels: category/portal
