### ISSUE TITLE
NotSupportedException - "Newtonsoft.Json.Linq.JArray" is not supported

### ISSUE THREAD

**Issue by giordanop** [umbraco/Umbraco.Cloud.Issues#158] opened 2020-01-20 12:38 UTC
Recenlty updated to 8.4.1 Umbraco instance throws an error when transferring the content from local to dev (but also when restoring).

"The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API has thrown an exception. It might have been caused by an inner System.NotSupportedException with message: Value of type "Newtonsoft.Json.Linq.JArray" is not supported."

Umbraco support says that issue is caused by the parentheses in one of the values of the property of a datatype, but after having replaced the parentheses and re-saved the node, the error is still thrown. 

![image](https://user-images.githubusercontent.com/11761097/72726865-c501a880-3b89-11ea-9299-9b169c487d4a.png)

Umbraco 8.4.1
Deploy 3.3.0

**Comment by jpinto3488** [comment] 2020-01-29 11:07
Same issue, running Umbraco Cloud 8.5.3 with deployment 3.3.0
I have this issue with nodes containing nested elements. We currently have about 30 different content types that can be used as nested elements, currently if 5 of them are inserted into a node, restoring that node will be impossible, due to error "Value of type Newtonsoft.Json.Linq.JArray is not supported." or "Value of type System.Int64 is not supported.".
Spent an entire day trying to identify what may be causing the issue, tried to delete doctypes, recreate them, rename them, changed properties, tried everything.
Just couldn't find what is causing the issue. If I create an exact same copy of that content type, it will work, but sometimes not.
Logs do not help, as there are no information regarding the error.

**Comment by jmayntzhusen** [comment] 2020-01-29 11:59
Hey @giordanop & @jpinto3488 

We have no been able to reproduce this issue, so you may have done something very specific for your data to end in a state that Deploy can't handle. Could either of you reach out to the Umbraco support and reference this message, then we can get access to your data (with your consent ofc) to figure out what happened.

@jpinto3488 

The "Value of type System.Int64 is not supported." is a seperate one, and will be fixed in next Deploy release - you can get a hotfix version here: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/151#issuecomment-578065571

**Comment by nul800sebastiaan** [comment] 2020-01-29 13:29
I'll close this for now as not reproducible, if you have new steps to be able to reproduce then we're all ears of course. Hope you managed to get it sorted through support though!

**Comment by jpinto3488** [comment] 2020-01-29 16:39
Ok, now I understood what is the issue and is easy to reproduce.
First of all, I installed the hotfix UmbracoDeploy.v3.3.1-alpha-20200124-004.zip mentioned here https://github.com/umbraco/Umbraco.Cloud.Issues/issues/151#issuecomment-578065571

Correctly installed in all environments and working on most situations.
the Newtonsoft.Json.Linq.JArray error happens only when you try to restore a nested element, which has a multiple media picker property, if that property has selected some medias that are missing on the destination environment.

To reproduce the issue:
- Local: Create doctype "NestedElement" as an ElementType with multiple media picker field "MediaItems"
- Local: Create doctype "Page" with property "NestedElements", which allows the "NestedElement" inside.
- Push local to live to create new doctypes on live env.
- Live: Add some media items (I used images)
- Live: Create node of type "Page", add a "NestedElement", pick some media items on the nested element fields (those media items should actually be available only on live env.)
- Local: Partial restore the newly created node
- Local: The partial restore will succeed and create the node on local, BUT the mediapicker will be empty.
- Local: Try again partial restore on the same element, the system will try to update the existing node, but will return the Newtonsoft.Json.Linq.JArray error.

Note: if the media items are already available on the local env., the restore will succeed. The error happens only if the media items are only on live.

**Comment by jmayntzhusen** [comment] 2020-02-04 12:11
Thanks for the clarifications @jpinto3488

We can confirm that this is still an issue and is something we can reproduce for several different data types within nested content. 

We have some sites to test with from helpful Cloud users based on my previous comment. Will update here when we have more information 🙂

**Comment by hfloyd** [comment] 2020-02-13 22:43
I'm having the same issue with a child site from a Baseline. The child site had demo content restored from the Baseline to the "Live" cloud environment, but when I attempt to start working on it locally , I am unable to Restore from the Live environment. 

Perhaps if there were a way to restore the Media separately from the Content, we could work around this issue...

**Comment by jpinto3488** [comment] 2020-02-14 18:00
is there any hotfix or timeline for this bug to be fixed? We are working on a very big website with PRO plan, which is scheduled to go live in a month and we are stuck not being able to transfer content from an environment to another, live, dev local, none of them work when there are nested elements with media involved. Now it's more than 2 weeks that we are unable to transfer content and I am running out of excuses with the customer.
Thanks

**Comment by verookasalt** [comment] 2020-02-14 19:47
Like jpinto above, I too wonder when this will be fixed. I have spent the better part of a week trying to get a simple site setup with a theme only to get this error. We need to have some idea as to when this issue will be resolved. 

Until then, I simply cannot recommend Umbraco Cloud to my customer.

**Comment by johnk-granite** [comment] 2020-02-17 13:05
We're having this issue too on a site thats due to go live early next week. Is there any timeline on a fix or at least a workaround?

**Comment by jwc3** [comment] 2020-02-18 08:05
We also have this problem. Can you tell us what it looks like with a fix? For a while, our customer can change the content directly on live instead of the usual way on stage and then push the content to live. But in the long run, our customers won't like that.

**Comment by lukehook** [comment] 2020-02-18 17:01
@nul800sebastiaan we're experiencing this with Child baselines also. We have a project going to production in a couple of weeks and we're currently unable to restore content locally due to 'System.NotSupportedException: Value of type "Newtonsoft.Json.Linq.JArray" is not supported.' error. As this is now easily replicable is there any timeline on a possible fix or can this ticket at least be re-opened as the initial bug has not been resolved.

**Comment by marols** [comment] 2020-02-20 13:01
I am experienceing the same problem.

**Comment by jmayntzhusen** [comment] 2020-02-24 11:20
Hey all

This issue will be fixed in the next minor release, Deploy 3.4.0.

We can't say exactly when this will be released on Cloud yet, but should be soon. In the meantime if anyone is blocked from deploying on their projects you are welcome to use the new build which can be found here: http://nightly.umbraco.org/?container=umbraco-deploy-release

**Closed by jmayntzhusen** 2020-02-24 11:20 UTC
Labels: category/umbraco-deploy, state/in-sprint

**Comment by marols** [comment] 2020-02-24 14:51
Great news! Thank you

**Comment by dpedrovich** [comment] 2020-02-26 08:20
I experienced similar issues with Newtonsoft: 

"System.NotSupportedException: Value of type "Newtonsoft.Json.Linq.JObject" is not supported.
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception."

Using the new build (Deploy 3.4.0) solved the problem for me.
