### ISSUE TITLE
CI/CD Deployment Stopped Working After Umbraco Autoupgrade

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Cloud.Issues#737] opened 2024-02-15 00:41 UTC
### Issue description

I have an umbraco cloud project that connects to a github repository with multiple csproj files using the ci/cd flow documented [here](https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/umbraco-cicd/samplecicdpipeline/github-actions). It worked fine initially, but after the recent update from 13.1.0 to 13.1.1, it stopped working. The initial error I got can be seen below.

![initial-error](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5932368/e75ee57f-4411-4836-8cfa-9bc60bc6c377)

That error is understandable, and it looks like umbraco cloud updated the package versions on the github repository automatically, though it didn't update the Umbraco.Cms.Imaging.ImageSharp library for some reason (I manually updated it to match the current umbraco version). However, after pulling down those updates and deploying again, I now get a different error earlier in the deployment process.

![current-error](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5932368/e2457812-a485-4f57-8c00-d996310da994)

There might be a race condition, as the initial commit that failed happened just one minute before umbraco cloud committed the updates with the package changes, so I assume my initial commit happened while umbraco cloud was in the middle of upgrading.

I did notice a slight issue with my setup after rereading the instructions. I had added the line to ignore "**/git-patch.diff" to cloud.gitignore instead of .gitignore (the way it's worded in the instructions can refer to both files). However, I fixed that and removed the patch file from version control and I still get the same error.

Is there something I need to adjust on my end to fix this, or is this an issue umbraco cloud or the deployment scripts (I'm using the powershell scripts)?

**Comment by sajumb** [comment] 2024-02-15 08:12
Hi @jaandrews 
It seems like you're encountering a specific issue related to the CI/CD flow in Umbraco Cloud, particularly after an update from version 13.1.0 to 13.1.1. Your detailed description suggests a complex situation that could involve a combination of factors, including potential race conditions during the update process, and issues with package versioning, especially regarding the `Umbraco.Cms.Imaging.ImageSharp` library.

Given the complexity and specificity of the issue, it's recommended to directly contact the CI/CD support team for more personalized assistance. You can reach them at umbraco-cicd@umbraco.dk. When reaching out, be sure to include:

- **Your project alias**: Providing this will help the support team to quickly locate your project in their system and understand the specific setup and context of your issue.
- **A detailed description of the issue**: pretty much just a copy of the fine description you posted above.

The CI/CD support team is well-equipped to handle such inquiries and can provide you with the most accurate and timely assistance. They may also be able to provide insights into whether the issue is on your end or if it's related to the Umbraco Cloud infrastructure or deployment scripts you're using.

**Comment by jaandrews** [comment] 2024-02-15 18:03
@sajumb I've reached out to the support team. Will follow up on this thread with whatever comes out of that. I do suspect the Umbraco.Cms.Imaging.ImageSharp is a library that should be upgraded by the auto upgrader though, so that should be addressed before this thread is closed unless there is a reason it's not.

**Comment by jaandrews** [comment] 2024-02-16 17:59
I got a solution from umbraco's CICD team. The fix for the deployment issue was to comment out the "cloud-sync" job in main.yml and trigger a deployment. Once I did that, and then reverted that change, the deployments worked again. See below for details of the change.
![deployment-script-change](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/5932368/18c561f6-2f32-4528-86d7-382c9f8f85b5)

I haven't closed this since I'm not sure whether the Umbraco.Cms.Imaging.ImageSharp library is supposed to be autoupgraded, but the bulk of my issue is resolved by that.

**Comment by mclausen** [comment] 2024-03-04 12:53
Hi @jaandrews good to hear that you got it working!
When upgrading a cloud site, the platform relies on the dependency tree that comes with the CMS packages. So when upgrading from 13.1.0 to 13.1.1, the `Umbraco.Cms.Imaging.ImageSharp` was automatically bumped as well.

I will be closing the issue for now, but feel free to reach out either here, or by [umbraco-cicd@umbraco.dk](mailto:umbraco-cicd@umbraco.dk) if you've have further questions :)

**Closed by mclausen** 2024-03-04 12:53 UTC
