### ISSUE TITLE
Umbraco nuget missing when using UaaS.cmd

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#67] opened 2019-03-27 09:04 UTC
When starting a visual studio project using UaaS.cmd there is no Umbraco nuget package included in the .Web project. This creates issues when installing aditional nuget packages.

Reproduction
------------

- Start a visual studio project using UaaS.cmd
- Open the solution
- Install a nuget package depending on Umbraco (e.g. DocTypeGridEditor)
- UmbracoCms 7.1.x get's installed because that's the min version of DTGE

If Umbraco was in the package list it would meet the min version and leave Umbraco as is. Now it breaks the project.

**Comment by FransdeJong** [comment] 2019-04-03 07:23
To add to this issue. I often run into issues when the cloud project is updated. The visual studio project doesn't know about the update and I get conflicts. The solution is to update the web nuget package to the version updated by cloud. 

It looks like not all dependencies update to the same version as the Umbraco nuget package?

**Comment by nul800sebastiaan** [comment] 2019-09-02 06:33
I've tested this again and I believe we updated the UaaS.cmd tool since this issue was made, I can't reproduce the problem at the moment, UmbraocCms / UmbracoCms.Core are added correctly. 
I'll close this for now.

**Closed by nul800sebastiaan** 2019-09-02 06:33 UTC
Labels: state/hq-discussion-cloud, state/inbox
