### ISSUE TITLE
Autoupgrade fails if you are using a local package source

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Cloud.Issues#610] opened 2022-10-31 12:51 UTC
### Issue description

If an auto upgrade is running, and you are using a local NuGet source (eg. a folder that sits in the repo) the upgrade will fail, since it cannot access the NuGet source. This happens for upgrades that are automatically rolled out, and for upgrades where you have to press a button to roll out the upgrade.

**How to reproduce**
1. Add a new local package source to the NuGet.config in the root of the repo like this:
` <add key="umarketingsuite" value="C:\home\site\repository\umarketingsuitepackages" />`
2. Wait for an autoupgrade to roll out - it will fail, and give you the error message listed below.

**Error message show in the portal**
`Latest upgrade has failed - Error restoring packages: Determining projects to restore... /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. /app/work/repository/src/UmbracoProject/UmbracoProject.csproj : error NU1301: The local source '/app/work/repository/C:\home\site\repository\umarketingsuitepackages' doesn't exist. Failed to restore /app/work/repository/src/UmbracoProject/UmbracoProject.csproj (in 125 ms). `

**Comment by sitereactor** [comment] 2022-10-31 15:24
What is the expected behaviour here?
That Cloud detects local nuget sources and the creates the folder, so it will be an empty package source?

Follow up question:
Does the solution use packages in the local package source, which are not available anywhere else? (Meaning the nuget is not committed to the repository folder, and the package or its version is not on nuget)

**Comment by hjaltedaniel-umbraco** [comment] 2022-10-31 16:07
Expected behavior: The project should build fine after an auto-upgrade - which is the behavior on a regular deployment.

The packages, in this specific case, sit just in the local package source (which is part of the repo), that is pushed to Cloud. They are not available anywhere else.

**Comment by sitereactor** [comment] 2022-10-31 16:10
Alright, so it's within our autoupgrade "verification build" that it breaks. Within the service not the deployment pushing the upgrade. Makes sense. Think I misunderstood where in the flow it was failing.

This is a bug for the Platform team.

**Comment by mclausen** [comment] 2022-11-01 09:32
Howdy @hjaltedaniel-umbraco! That is an interesting bug indeed!

After reading through the issue that are some things that come to mind.

1. The local package source that is referenced `<add key="umarketingsuite" value="C:\home\site\repository\umarketingsuitepackages" />` is an absolute path on a disk, on a windows environment. The first thing is this needs to be a relative path from the csproj. 
2. In general I would consider it bad practice to have a reference to a NugetFeed on a local drive, and also whether or not we want to recommend this on Cloud. 
3. The package feed that you are referencing `umarketingsuite`. Assuming this is the NuGet packages for uMarketing suit, arent the packages on Nuget.Org good enough?

**Comment by hfloyd** [comment] 2022-11-08 18:42
I've noticed this issue as well.

**I DO think repo-only NuGet packages need to be supported.** I use them for my own projects - where I am testing patch updates on my own (otherwise publicly-available) NuGet packages, but also, because NuGet is the ONLY way to add in external libraries, many developers will have some private/proprietary code which will need to be added via NuGet - but otherwise the package shouldn't be generally available. 

For my own projects, I have a root-level "PrivatePackages" folder to store any non-public NuGet packages:
![image](https://user-images.githubusercontent.com/1252593/200648165-6f3d81a4-91a7-4aa6-b0c8-09c9c8631ccd.png)

And the NuGet.config looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
	<add key="Private Packages" value="PrivatePackages" />
  </packageSources>

  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  
</configuration>
```

Except for the issue @hjaltedaniel-umbraco mentions, this works just fine on Umbraco Cloud.

**Comment by meyntony** [comment] 2023-09-08 07:28
@sajumb Doesn't this feature https://docs.umbraco.com/umbraco-cloud/set-up/private-nuget-feed resolve this issue?

**Comment by sajumb** [comment] 2023-09-08 09:45
Yes, we advise following the handling of private NuGet feeds as listed in the documentation you are referencing. By doing so, and storing relevant information/keys in shared secrets, the auto-upgrade should run smoothly.

Can you confirm, @hjaltedaniel-umbraco? If so, feel free to close this issue.

**Comment by hfloyd** [comment] 2023-09-08 11:27
Well, sorry guys, I'm not going to add that financial overhead the docs are suggesting to all my cloud projects. Would changing the path to be relative to the csproj file resolve the issue?

~Heather

Sent from my phone
________________________________

**Comment by bergmania** [comment] 2023-10-09 11:44
Hi @hfloyd.

I can see you are not doing exactly like I do when I test, as we talked about. Maybe you can test my way.

- Create a folder named "NuGetSource" i root
- Add NuGet packages to "NuGetSource" (In my example its just an unreleased version of Umbraco)
  -  ![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/1561480/e833e7a3-7bcc-4f83-84da-a91390d8a77d)
   - Add all the files to git
- Update the csproj file with the following
```xml
<PropertyGroup>
    <RestoreAdditionalProjectSources>
        $(MSBuildThisFileDirectory)/NuGetSource/
    </RestoreAdditionalProjectSources>
</PropertyGroup>
```

- Update the nuget package to the version in the NuGetSource folder
  -  e.g. 
 ```xml
  <ItemGroup>
...
    <PackageReference Include="Umbraco.Cms" Version="9.1.1-preview20211119.77615" />
...
</ItemGroup>
```

**Comment by hfloyd** [comment] 2023-10-09 19:45
Thanks, @bergmania , So it looks like your main suggestion is that I move the package files inside the UmbracoProject - rather than using the Git root (outside of the Umbraco Project folder). I will try this once I see there is a patch update scheduled.

**Comment by bergmania** [comment] 2023-10-12 10:26
My main suggestion is to use the `RestoreAdditionalProjectSources`. I would guess the location of the files is not important

**Comment by bergmania** [comment] 2023-10-14 16:03
I'm afraid it needs to be in all. But that could be done using a `Directory.Build.props`. There is examples in Umbraco codebase about how to use such files

**Comment by hfloyd** [comment] 2023-10-18 22:08
Ok, I'll update all my projects with:

```
	<PropertyGroup>
		<RestoreAdditionalProjectSources>
			../../PrivatePackages/
		</RestoreAdditionalProjectSources>
	</PropertyGroup>
```

to reflect the location of the folder in my solutions.

**Comment by sajumb** [comment] 2023-10-24 19:04
Great, thank you for the input @bergmania.
We are closing this issue.

**Closed by sajumb** 2023-10-24 19:04 UTC
Labels: type/bug, category/platform
