### ISSUE TITLE
Baseline childrens Transform configs, gets overwritten from the Baselines transforms config.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#53] opened 2019-02-14 14:29 UTC
A brief description of the issue goes here.

If you have a Baseline project, that has its own transform config, it will affect the child projects which is based on the baseline. This is due to the naming convention of the transforms as the name "live" will end up affect any live environment, no matter which project the transform was meant for. 

Reproduction
------------
In order to reproduce this, you will need a **Baseline project** at least **a child project based on the baseline**.
Individual transforms for both the Baseline and the child project.

### Bug summary

The baseline transform will overrule the Child transform, as it is named web.live.xdt.config.

The problem is that you have to include the live in the transform file name, in order to apply the transform the live environment. 

### Specifics

Umbraco 7.13.2
Forms 7.0.6
Deploy 2.0.15

### Steps to reproduce

1. Establish baseline project.
2. Make at least one child.
3. Upload a transform file to the child project, by cloning it down and apply the child.Web.Live.xdt.config to the child project, by adding it into git. This one only changes my <mailSettings>
4. Upload a transform file to the Baseline project. The one I made, transform my redirects. I have this one, Web.Live.xdt.config.
5. Send an updated document type to the baseline child. 
6. You now see that, my transform for my <mailSettings> has not been applied and instead the baseline Transform has been applied in my web.config changing my Redirects. 

### Expected result

Seeing the child transform being applied on my web.config.

### Actual result

Instead I now how both the child.Web.Live.xdt.config and the Web.Live.xdt.config and the latter tranform config overrules the child one.

![image](https://user-images.githubusercontent.com/32164310/52793145-52c93f80-306d-11e9-87d2-6638d0c0da94.png)

**Comment by carlkentor** [comment] 2019-03-27 08:35
I can confirm this issue as well. It seems like the transforms get executed alphabetically. Since our projects starts with letters before W the Web.Live.xdt.config overwrites our child.Live.xdt.config transforms. :/

**Comment by CaB-Studios** [comment] 2019-03-28 13:35
I am experiencing the same issue albeit we are prefixing the config transform files with the project aliases but finding that both master and child transforms are being applied (despite the master alias not matching the child project).

In one incident this led to duplicate rewrite rules with the same name added to a config file which took the site down.

**Comment by MichaelNielsenDK** [comment] 2019-04-30 08:29
I feel that this is somewhat related to this
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/22 

Right now, to get around this issue, you'll have to make sure you do not have a web.live.config transformation file on the baseline, and connect to every single child and upload a transformation file there. 

My suggestion would be that any transformation files prefixed with project name takes priority over any other.

**Comment by nul800sebastiaan** [comment] 2020-02-19 09:11
Just as an update, we've not been able to prioritize this issue yet and are putting it on our list of future ideas to work on around baselines when we get a bunch of baselines features that we can work on in a bundle.

**Comment by sajumb** [comment] 2023-10-04 14:39
We are closing this issue as this now seems outdated and won't have an impact on the latest four major versions.

**Closed by sajumb** 2023-10-04 14:39 UTC
Labels: status/idea, category/platform, project/baselines
