### ISSUE TITLE
Umbraco.DropDown.Flexible data type not syncing

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Cloud.Issues#20] opened 2018-11-06 23:11 UTC
When the (relatively) new built-in `Umbraco.DropDown.Flexible` data type is used (all other 4 are now depreciated in https://github.com/umbraco/Umbraco-CMS/pull/2502), the selected values aren't synced between environments.

Reproduction
------------
- Add a `Umbraco.DropDown.Flexible` property to a document type and add some pre-values
- Create a node of this document type and select a value from the drop-down
- Sync the node to another environment (e.g. Local to Live) using Deploy
- The node now exists on the Live environment, but the drop-down doesn't have a selected value

### Expected result
The property on the destination environment should have the same selected value as the source.

### Actual result
The property on the destination environment doesn't have a selected value.

Workaround
------------
Fixing this issue is very simple: just add `Umbraco.DropDown.Flexible` (or actually the `Constants.PropertyEditors.DropDownListFlexibleAlias` constant) to the property editor aliases in the `PrevalueValueConnector`.

As a temporary workaround, I'm currently adding this class to our projects:
```c#
public class DropdownFlexiblePrevalueValueConnector : PrevalueValueConnector
{
    public DropdownFlexiblePrevalueValueConnector(IDataTypeService dataTypeService, ILogger logger)
        : base(dataTypeService, logger)
    { }

    public override IEnumerable<string> PropertyEditorAliases => new string[] { "Umbraco.DropDown.Flexible" };
}
```

**Comment by mniederkofler** [comment] 2018-12-07 10:09
I am experiencing the same issue on Umbraco Cloud.
Property values are always gone, when the node is restored to the local environment or pushed to the live environment.

**Comment by mikkelhm** [comment] 2019-01-14 13:22
This will be fixed and included in the upcomming deploy release v. 2.0.15 - It will be released tomorrow.

**Comment by mindrevolutiontk** [comment] 2019-02-05 09:08
We have just performed a test installation of Umbraco Cloud with version 7.13.1 and Deploy 2.0.15. The described problem still exists. The described workaround does not work either. Maybe it doesn't work anymore due to the update of Deploy?
This is an absolute no-go for our work, how are we supposed to explain to our customer that he has to set the status again manually for 1000 nodes.

**Comment by esn303** [comment] 2019-02-05 09:19
Do you have any project on Deploy 2.0.15 with your workaround applied @ronaldbarendse? Keen to find at least a temporary fix.

**Comment by AmalieWowern** [comment] 2019-03-12 11:06
I can also confirm that this has not been solved

**Comment by AmalieWowern** [comment] 2019-03-26 13:10
Is it possible to get this issue reopened?

**Comment by ronaldbarendse** [comment] 2019-03-26 14:54
@esn303 Looks like `Umbraco.DropDown.Flexible` is added to `Umbraco.Deploy.ValueConnectors.PrevalueValueConnector` in 2.0.15, so the supplied workaround is not needed and may actually conflict if you're still using it with this version.

**Comment by greystate** [comment] 2019-03-26 15:53
@ronaldbarendse I don't understand this... I didn't have any workarounds installed and I was on Deploy 2.0.15 when experiencing [the above](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/20#issuecomment-466033623) data-loss.

Are you saying it's working for you now, out of the box?

**Comment by esn303** [comment] 2019-03-27 08:53
@ronaldbarendse @greystate Was wondering the same. Because it's not working for me on a fresh instance right now. Did I miss something?

**Comment by ronaldbarendse** [comment] 2019-04-17 08:34
Just to get back on this: it's working for me now, yes 😉 So it might be some other error, .e.g. because the pre-values (the texts) are combined with `;;` in the Deploy connector or some other specific implementation detail...

**Comment by Aaen** [comment] 2019-06-17 09:13
@mikkelhm I have tried to reproduce this issue again on:

Umbraco 8.0.2
Forms 8.1.1
Deploy 3.0.1

I am able to reproduce this issue when I am using the Umbraco.DropDown.Flexible data type and choose a value in a dev environment. Save this and transfer it to live, then the drop down does not have the picked value chosen in the drop-down list. 

The values are there but nothing is picked.

**Comment by Aaen** [comment] 2019-06-19 13:39
@jmayntzhusen I can now confirm that this issue is fixed for:

Umbraco 8.0.2
Forms 8.1.1
Deploy 3.0.2

**Comment by nul800sebastiaan** [comment] 2019-06-19 13:55
👍  thanks Dennis.

**Closed by nul800sebastiaan** 2019-06-19 13:55 UTC
Labels: category/umbraco-deploy, type/bug

**Comment by c9mbundy** [comment] 2021-11-27 07:12
I'm encountering this issue on Umbraco-Cloud with Umbraco-7.15.7 and Deploy-2.1.4

Deploying a change to a doc-type containing properties based on an Umbraco.DropDown.Flexible results in the Selected value of existing data being 'lost' - an effective data-loss condition.

This was discovered by a very unhappy client who lost data on 200 odd nodes, but I have other clients where a similarly requested change to add a field to a doc-type could result in 1500 or more nodes losing their current selected values for existing dropdown fields.

Presumably this issue is still caused by Deploy-2.1.4 ?

Is there a fix or workaround for this combination to stop this data-loss on deploy ?
