### ISSUE TITLE
Unable to obtain configuration on local login

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#342] opened 2021-03-22 20:03 UTC
When I run a local project and login for the first time straight away I get this error.
If I wait a few minutes it's gone. It's not blocking but it is certainly annoying.

![image](https://user-images.githubusercontent.com/29602162/112051058-c5148400-8b51-11eb-82cf-a7ce1fe77d45.png)

**Comment by RyuLindow** [comment] 2021-03-22 20:12
I've recorded this exact same error a bit over 2 months ago when I was testing UmbracoID locally with the internet turned off.
Here's the video I've recorded back then - https://www.dropbox.com/s/aqcdbgfdg3pkbmu/0aPyQ2ZnD9.mp4?dl=0

Which version of UmbracoID are you using? You can check it by checking the properties of the `Umbraco.Cloud.Identity.Cms.dll` which is located in the bin folder and then going to the details tab.

Also, it would be great if you could provide a bit more info in general.

Versions, steps to reproduce, etc.

**Comment by FransdeJong** [comment] 2021-03-22 20:15
I've seen it on v3.0.140.0 twice today.

I'm not sure about the repro but it looks like running the project and trying to log in as soon as it's started umbraco.
After the first successful login it doesn't happen again.

**Comment by RyuLindow** [comment] 2021-03-22 20:36
Cool dashboard. Don't pick if I grab the files and give a test ride 😏

By the way, I've just tested on v3.0.140.0 too and:

**With internet**
1. Spin up the site using vs code and is
2. Go to /umbraco
3. Click on the "Sign in with Umbraco" button
4. Login instantly

**After I turned off the WiFi**
1. Repeat steps 1-3
2. Get this
![image](https://user-images.githubusercontent.com/56826332/112054677-23436600-8b56-11eb-9303-1da66b8fed5a.png)
3. Click the same button again and then I get this instead which is the same error you're getting
![image](https://user-images.githubusercontent.com/56826332/112054868-6f8ea600-8b56-11eb-8787-6b509e5aa64d.png)

I don't really know why this is happening but it looks to be something with the connection 🤔

Sadly, I can't reproduce with WiFi turned on :(

**Comment by FransdeJong** [comment] 2021-03-22 20:38
I'm running the solution in VS2019, so maybe that's slower starting up?

**Comment by RyuLindow** [comment] 2021-03-22 20:40
Yeah, that sounds plausible 🤔

Did you clone it using the UaaS.cmd or?

**Comment by FransdeJong** [comment] 2021-03-22 20:42
Yes I did.
And these are both sites that have some content in it. But that shouldn't make any difference in my opinion?

**Comment by RyuLindow** [comment] 2021-03-22 20:56
I really can't reproduce this :(

1. Cloned it using UaaS.cmd.
2. Spun it up in my VS2019 both with and without debugging.
3. I always log in seconds after I click on the blue "Sign in with Umbraco" button.

When you said that you've seen it twice, was it on two different projects or on the same one?

**Comment by FransdeJong** [comment] 2021-03-22 20:58
I've had it happen on 3 projects up until now.

**Comment by RyuLindow** [comment] 2021-03-22 21:07
Can you check in the chat support when you have the time and mention me by name?

Then you could invite me to either of the 3 projects and I could try to repro on yours instead.

I don't really want to share my mail here 😐

Unless you remember it :)

**Comment by FransdeJong** [comment] 2021-03-22 21:09
Let's see if someone else runs into this first?
Maybe it's only on my machine. I just wanted to document it so it doesn't get lost.

I don't want to waste your time ;)

**Comment by RyuLindow** [comment] 2021-03-22 21:10
This would take max 5-10min, so it's not a problem :)

Fair enough. Let's see if someone else reaches out 👍

**Comment by FransdeJong** [comment] 2021-03-23 18:03
Another variation:
![image](https://user-images.githubusercontent.com/29602162/112195589-6e1eb580-8c0a-11eb-9743-908e6ed6f900.png)

**Comment by FransdeJong** [comment] 2021-03-23 18:03
I'll keep on logging the errors until I can reliably reproduce them.

**Comment by emma-hq** [comment] 2021-03-24 13:23
Thanks Frans. I'll leave in the capable hands of @RyuLindow for now

Emma

**Comment by FransLammers** [comment] 2021-12-01 15:07
I get this same problem on regular basis. 
Like just now I cloned an existing project to my own machine, opened it in VS2022 and this error was showing: 

IDX20803: Unable to obtain configuration from: '[PII is hidden]'.

After trying a couple of times I finally logged in.

**Comment by dawoe** [comment] 2022-03-30 07:12
I see this happening on V9 project I run locally as well

This is the stack trace

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Umbraco.Deploy.Infrastructure.Middleware.BearerTokenAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Most of the time clearing cookies and restarting application solves it,

**Comment by FransdeJong** [comment] 2023-05-31 15:12
I just ran into an error on a V10 site as well:
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/29602162/e58c3926-3b01-43ab-89bf-e1fce6808ccf)

**Comment by ronaldbarendse** [comment] 2023-05-31 15:23
Looking at the stack trace that Dave and Frans posted, this seems to happen on intermittent connection issues when trying to retrieve the OpenID Connect configuration from a remote endpoint. @sajumb This could be made more robust by implementing retry policies and handling the exception in a nicer way (even if it's just wrapping it in another exception that has a more descriptive message).

**Comment by FransdeJong** [comment] 2023-05-31 16:19
It happened for about half an hour today only with the local install. Everything else was fine...

It completely blocks Umbraco since we don't have local users and it somehow always happens when we have a tight deadline 😅

**Comment by mclausen** [comment] 2024-07-15 13:02
Howdy there, folks 🎩

It looks like a lot of water has flowed under the bridge since the last comment! As @sajumb mentioned, we did look into this ticket… which was back on September 6th, 2023!

Back then, we closed the issue but never replied to this ticket. Oops! 😅

I’m closing the issue for now, but please don’t hesitate to re-open it if it’s still a problem.

Kind regards,
@mclausen - Cloud Core Team Lead

**Closed by mclausen** 2024-07-15 13:02 UTC
Labels: state/needs-investigation

**Comment by nwahlberg** [comment] 2024-07-20 14:44
Hi all, sorry to say that it's still happening when developing locally. I'm on Mac, latest v of Umbraco. 

`IDX20803: Unable to obtain configuration from: 'https://identity.umbraco.com/tfp/5f36b6cc-f3ae-4a05-8ce1-826d1068a97d/B2C_1A_SignInLocal/v2.0/.well-known/openid-configuration'. Will retry at '7/20/2024 2:37:31 PM +00:00'. Exception: 'System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.`

![CleanShot 2024-07-20 at 10 44 13@2x](https://github.com/user-attachments/assets/81b41bf3-bf52-4e54-a4de-6a1bfbf4935c)
