### ISSUE TITLE
Content restore: Click outside of transfer UI, closes section

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Cloud.Issues#330] opened 2021-03-01 13:34 UTC
If you are in the process of restoring content, and you accidentally click outside of the transfer UI - the section closes down, and you have no way of following along with your content transfer.

Reproduction
------------

### Bug summary
Issue is seen on the newest version of Deploy - and happens both on full restore and partial restore.

### Steps to reproduce

1. Initiate a content restore
2. Click outside of the transfer area

### Expected result

You should not be able to exit the restore dialogue as long as the restore is ongoing.

### Actual result

The restore dialogue closes down - and you'll have to rely to your logs to find out if the restore succeeded.
![Restore fails](https://user-images.githubusercontent.com/61144403/109503958-3608d480-7a9b-11eb-982b-6e6d4562fb98.gif)

**Comment by nul800sebastiaan** [comment] 2021-03-01 13:47
That's a CMS issue, any action in the context menu will disappear when you click in the tree area.

**Comment by RyuLindow** [comment] 2021-03-01 17:10
Kinda already made an issue on this here - https://github.com/umbraco/Umbraco.Cloud.Issues/issues/304 :)

**Comment by nul800sebastiaan** [comment] 2021-03-03 12:59
I'll close as a duplicate of #304 👍

**Closed by nul800sebastiaan** 2021-03-03 12:59 UTC
Labels: state/needs-investigation
