### ISSUE TITLE
v8.1.1 - Variation "xx, <null>" is not supported by the property type

### ISSUE THREAD

**Issue by ylinssen** [umbraco/Umbraco.Cloud.Issues#108] opened 2019-08-12 17:22 UTC
We are currently facing an issue during the synchronization of content between environments. It seems to have something to do with content inheritance. It only occurs in sites that contain multiple languages and that have the allowance of varying per culture for one or more Document Types.

Reproduction
------------

### Specifics

**Versions(s):** Umbraco 7.X.X, 8.0.0, 8.1.0, 8.1.1, **8.1.2, 8.1.3, 8.1.4.**
**Deploy:** 3.1.1

**Error message**:
![image](https://user-images.githubusercontent.com/37552166/62883151-b4741900-bd33-11e9-9ccc-163bb10e5422.png)
_- Variation "xx, <null>" is not supported by the property type_

### Steps to reproduce
Since this issue doesn't always occur and the circumstances under which it does are not always the same, it's hard to write a detailed plan on how to reproduce this. Therefore I have described some factors that need to be present anyway. I will refine and update this issue as soon as I have more information available.

- Make sure that you have at least two environments within your Umbraco Cloud website.
- Make sure that your website contains multiple languages (at least 2).
- Create a new Document Type or modify an existing one and make sure that the "Allow varying per culture" setting's value is false.
- Add content, at least two levels, using this Document Type.
- To avoid potential errors that have nothing to do with this issue, make sure that you resolve all kinds of schema mismatches. Also, make sure that both environments are identical in terms of source code **and** Document Types.
- Start synchronizing content using the 'Queue for transfer' mechanism.

### Expected result

- Perfectly synchronized content.

### Actual result

- Aborted synchronization process. Please check the screenshot with the actual error message I have added above.

**FYI:** A temporary workaround, which is setting the "Allow varying per culture" value to true, has been provided, but this is unfortunately not acceptable under all circumstances.

### Potentially related issues
- https://github.com/umbraco/Umbraco-CMS/issues/6101
- https://github.com/umbraco/Umbraco-CMS/issues/5909
- https://github.com/umbraco/Umbraco-CMS/issues/5817

---
_This item has been added to our backlog [AB#2692](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2692)_

**Comment by opc-clienti** [comment] 2019-09-13 10:06
We've seen this on two seperate projects. But unlike OP, we get "Variation "<null>,<null>" is not supported by the property type". For both projects, we first created all content on one language, and didn't enable vary by culture until after the site was initially live.

In the most recent case, the document in the error message actually only consists of compositions, and doesn't have any properties on it's own.

**Comment by OlePc** [comment] 2019-09-13 10:14
We've seen this on two seperate projects. But unlike OP, we get "Variation "<null>,<null>" is not supported by the property type". For both projects, we first created all content on one language, and didn't enable vary by culture until after the site was initially live.

The first project was born on v8, but didn't have multiple languages until the site was actually live, and the client requested the site to be multilingual. 

The second and most recent project as a v7 site migrated to v8 using the migration tool. So, as for the first project, vary by culture was enabled to a project already filled with content on one language. Turned out to be only one doc type it was complaining about, which only consist of compositions.

This is a blocking issue for us in order to use and recommend Umbraco 8 to our clientis.

**Comment by oleksandrmerchanskyi** [comment] 2019-09-18 08:41
Hey, we receiving on the same error when we trying to migrate content from "development" to "live". It's a bit critical for us because we should use "development" for production which runs other problems with site crashes.
![image](https://user-images.githubusercontent.com/11855479/65129510-1a735080-da04-11e9-80b0-6030adf1f746.png)

**Comment by ylinssen** [comment] 2019-09-25 09:38
The issue was created 45 days ago. Still no comment or solution..

**Comment by nul800sebastiaan** [comment] 2019-09-25 09:47
Hmm, I could have sworn this was a duplicate of another issue, which had a comment on it. 😐

Sorry for not updating this, we're working on the issue in our current sprint and will update when we have a fix.

**Comment by warrenbuckley** [comment] 2019-09-25 13:56
Here is a CI build from our build server that you can use.
You will need to update the DLLs in your development cloud site and push/transfer this file change via the Cloud portal.

With these new DLL/fix you should be able to transfer content from Dev to Live that has content in another language.

[UmbracoDeploy.v3.1.2-alpha10326.zip](https://github.com/umbraco/Umbraco.Cloud.Issues/files/3652851/UmbracoDeploy.v3.1.2-alpha10326.zip)

**Comment by OlePc** [comment] 2019-10-09 06:34
Latest Umbraco Deploy didn't solve the issue for us. We still get Variation "<null>,<null>" on multiple projects when restoring. Since my last comment we created two new projects where the issue is also present.
Only solution so far is to delete and recreate the content, but that's not always an option.

What do you need from me in order to get closer to a solution?

**Comment by Prizonic** [comment] 2019-10-17 12:29
We are also experiencing the same issue, we can't restore content from umbraco cloud development to our local dev machine. We have also added an extra language variant after the content was created and since that we have experienced this problem when trying to restore content.

We are getting the error:  It might have been caused by an inner System.NotSupportedException with message: Variation "<null>,<null>" is not supported by the property type

Version: Umbraco CMS @ 8.1.5
Umbraco Deploy @ 3.1.4

**Comment by nul800sebastiaan** [comment] 2019-10-18 08:31
Thanks @OlePc and @Prizonic for the updated reports. This issue was closed since we did fix errors that look similar to this one in Deploy 3.1.3. Clearly, this was not enough and we need to figure out what the additional problem is. I notice the error is different from the original report, so that might be a clue. 

I'll mark this specific error as fixed and I've opened a new issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/135

Can you please help with some details and steps to try to reproduce this specific error on the new issue? https://github.com/umbraco/Umbraco.Cloud.Issues/issues/135

Thanks!

**Closed by nul800sebastiaan** 2019-10-18 08:31 UTC
Labels: state/backlog, state/hq-discussion-cloud, type/bug
