### ISSUE TITLE
Installed packages not showing up in Packages tab

### ISSUE THREAD

**Issue by rensknoors** [umbraco/Umbraco.Cloud.Issues#117] opened 2019-09-06 12:25 UTC
Installed packages no longer show up in the **Packages** > **Installed** tab on the target environment after deploying to this environment. The package still appear to be installed as all the files from that package are still in place and working as usual.
Because of this issue you can no longer remove packages unless you manually remove each files.

Reproduction
------------

### Bug summary

Installed packages no longer show up in the **Packages** > **Installed** tab on the target environment after deploying to this environment.

### Specifics
**Version**: Umbraco 8.1.4
**Deploy**: 3.1.1

### Steps to reproduce

- Install package via the **Packages** or **Install local** option on your local or development environment
- Deploy changes to a staging or live environment

or

- Install package via the **Packages** or **Install local** option on your local or development environment
- Clone the *.Web folder to local with the UaaSClone.cmd tool

### Expected result

- Expected the **Packages** > **Installed** tab to show the same packages I installed on the previous environment.
- installedPackages.config shows the Installed Packages.

### Actual result

- **Packages** > **Installed** tab shows no packages at all. The package files are still there and working.
- The file installedPackages.config is empty.

---
_This item has been added to our backlog [AB#2696](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2696)_

**Comment by nul800sebastiaan** [comment] 2019-09-06 12:34
Have you excluded the `~App_Data/packages/InstalledPackages.config` file from git?

![image](https://user-images.githubusercontent.com/304656/64428131-3e08d380-d0b3-11e9-9c6c-54735c17388f.png)

Your `.gitconfig` file should have the following entry in it: 

```
App_Data/*
!App_Data/packages 
```

**Comment by nul800sebastiaan** [comment] 2019-09-06 12:36
To clarify: the way that the installed packages show up in the backoffice is by reading the `~App_Data/packages/InstalledPackages.config` file. If you do not commit and push that file to your Cloud site, you will not see the installed packages in the backoffice.

**Comment by rensknoors** [comment] 2019-09-06 12:42
We have not modified the .gitignore that is included in the default Umbraco Cloud setup and we still have those 2 lines in our .gitignore.

Just to be sure, this is our .gitignore:

```
syntax: glob
.git
*.obj
*.pdb
*.user
*.aps
*.pch
*.vspscc
[Db]ebug*/
obj/
[Rr]elease*/
_BuildOutput/*
.vs/
.vscode/

_ReSharper*/
*.ncrunchsolution
*.ncrunchsolution.user
*.ncrunchproject
*.crunchsolution.cache

[Tt]est[Rr]esult*
[Bb]uild[Ll]og.*
*.[Pp]ublish.xml
*.suo
[sS]ource
[sS]andbox
*.vs10x
*.orig
*.[Dd]ot[Ss]ettings
*.js.map
deploy.cmd

bin/NativeBinaries/*

packages/*
!packages/repositories.config

App_Data/*
!App_Data/packages

log.txt
data/deploy*

App_Plugins/UmbracoForms/[Ii]nstalled

/media/*
/data/Revision/documents/*
/data/Revision/media/*
/data/Revision/mediaproperties/*
/data/Revision/properties/*

node_modules/
bower_components/
```

**Comment by nul800sebastiaan** [comment] 2019-09-06 12:47
Right, I see what is going on, you are installing the package on your running Cloud site, correct? 

We encourage people to test installing package on a local clone first to make sure that they work and don't break your setup. If there is actually a problem you can easily start over. From there on, you push the changed files including `installedPackages.config` to Cloud and then your team also gets those changes.

I realize that some people are doing this the other way around and this is currently not supported. The workaround is to clone the site locally now and install the packages again, this will generate the correct `installedPackages.config` that can then be committed to git.

I'll mark this as a feature request for now.

**Comment by nul800sebastiaan** [comment] 2019-09-06 13:00
Aha.. So ignore me, the problem is this:

v7: `~App_Data/packages/installed/InstalledPackages.config`
v8: `~App_Data/packages/InstalledPackages.config`

So the `.gitignore` file is slightly off for v8! Sorry about that, we should get that fixed up! 👍

**Closed** 2019-09-25 09:34 UTC
Labels: state/estimation, type/bug
