### ISSUE TITLE
Show version number on overview

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#127] opened 2019-10-02 07:54 UTC
It would be great if we could have a Umbraco version number and maybe even a Forms version on the tiles in the overview. Now we have to click on every tile to see what version it is running.

This would also be of great value when if and when [this](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/46) issue is implemented so we can sort on version number.

**Comment by nul800sebastiaan** [comment] 2020-03-04 07:09
I'll close this as a duplicate of #46 which covers this as well.

**Closed by nul800sebastiaan** 2020-03-04 07:09 UTC
Labels: category/portal, state/needs-investigation, type/feature
