### ISSUE TITLE
Unable to restore content to brand new Development environment

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Cloud.Issues#254] opened 2020-09-16 08:27 UTC
Reproduction
------------

### Bug summary

On a brand new Development (DEV) environment created from an existing LIVE environment, we're unable to restore the LIVE site's content. The restore process fails after about 6 mins with the following error:

<img width="484" alt="Screenshot 2020-09-16 at 10 04 58" src="https://user-images.githubusercontent.com/5463/93310397-045dc300-f805-11ea-8885-984dbb85ca95.png">

<details>
<summary>Detailed error message</summary>
<pre>
15bb0c44 - Executing, 10% - Get remote session
15bb0c44 - Executing, 20% - Create manifest on source
15bb0c44 - Executing, 25% - Review manifest on target
15bb0c44 - Executing, 30% - Create package on source
15bb0c44 - Executing, 80% - Complete remote session
15bb0c44 - Executing, 80% - Process package on target
15bb0c44 - Executing, 80% - Exception!
15bb0c44 - Executing, 80% - Abort remote session
15bb0c44 - Executing, 80% - Restore caches and indexes
15bb0c44 - Failed, 80% - Total time 00:06:19.06.

EXCEPTION

(proper exception traces at the end of this log)
System.InvalidOperationException: Cannot save content with an empty name.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #3 failed for artifact umb://document-blueprint/553df18caedb488c9207b7ad3e44f9d5.

EXCEPTION:

Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #3 failed for artifact umb://document-blueprint/553df18caedb488c9207b7ad3e44f9d5.
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()

INNER:
  System.InvalidOperationException: Cannot save content with an empty name.
     at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.EnsureInvariantNameExists(IContent content)
     at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.SanitizeNames(IContent content, Boolean publishing)
     at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistNewItem(IContent entity)
     at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Create(TEntity entity, Action`1 persistNew)
     at Umbraco.Core.Persistence.Repositories.Implement.RepositoryBase`2.Save(TEntity entity)
     at Umbraco.Core.Services.Implement.ContentService.SaveBlueprint(IContent content, Int32 userId)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentBlueprintConnector.Process3(ArtifactDeployState`2 dart, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentBlueprintConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
</pre>
</details>

### Specifics

- The site is on Umbraco **v8.6.4**, Forms **v8.4.1** and Deploy **v3.4.5**
- The site has three languages set up (Danish, English and Norwegian).
- The site has two Content Templates (blueprints) defined for a specific Document Type

Talking to Support there seems to be a known issue where Variants and Content Templates causes this problem - the suggested workaround listed was to create a document based on the Content Template and transfer that to LIVE and then create a Content Template based on that document.

This is not an option, since the DEV environment has just been created from the LIVE site and thus doesn't contain any Content Templates. Right-clicking the Content Templates folder in the tree does allude to maybe being able to restore those, but that just restarts the full content restore process (which fails).

**Comment by greystate** [comment] 2020-09-16 10:48
**Update:** I managed to restore the complete site by partially restoring just the root Content node.

I know it's merely a workaround, but for anyone finding this, it'll be worth a try.

**Comment by nul800sebastiaan** [comment] 2020-09-16 14:59
Thanks @greystate - we have identified and fixed the issue, we're trying to get a new version of Deploy out as soon as possible to fix this problem. No more actions are needed on your side, you'll automatically get it.

**Comment by nul800sebastiaan** [comment] 2021-03-22 08:59
Hi again @greystate, looks like we forgot to close this one, it looks like this was fixed in a Deploy release in September. I will close this for now but if it's still something you can reproduce we will of course have another look.

**Closed by nul800sebastiaan** 2021-03-22 08:59 UTC
Labels: state/in-sprint, type/bug

**Comment by greystate** [comment] 2021-04-08 09:35
I just hit a very similar issue today. Same problem - add DEV environment - Full restore from LIVE fails with a couple of these:

```plain
Document type Text with alias 'TextBlock'
umb://document-type/766cc60622df43809a051a6f4a89a272
Property type 'bodyText' is different (group b3795eb3-1394-46fe-86c0-6485b1a86e83, ppty 13ad9a71-f3b3-441c-a2fe-979e4ce0759b).
```


Technical details reveals:

```plain
Umbraco.Deploy.Exceptions.RestoreSchemaMismatchException: Schema mismatch between environments. See 'Mismatches' for details.
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ValidateManifest>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<Proceed>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsyncSub>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.TargetRestoreWorkItem.<ExecuteAsync>d__14.MoveNext()
```

Version info: Umbraco **8.11.2**, Forms **8.6.1**, Deploy **4.0.5** 

@nul800sebastiaan Do you want me to add this as a new issue instead? It's does not seem to be related to Content Templates...

**Comment by nzsle** [comment] 2021-04-23 18:29
I am getting the same errors when trying to restore content from live to dev. Did you find a solution?

**Comment by reneemhaas-diagram** [comment] 2021-07-28 17:00
Ran into this issue today. I created a brand new dev + live site off of a baseline. Tried a full and partial restore on the dev site from baseline and had schema mismatches for 6 types. I am on Deploy 4.1.2.
