### ISSUE TITLE
Deploy contrib 3.0 - Nested content with checkboxes throwing an error: 

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#151] opened 2019-12-24 09:33 UTC
When trying to transfer/restore nested content with a checkbox property it fails with this error message:
```
System.NotSupportedException: Value of type "System.Int64" is not supported.
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
```

Reproduction
------------
### Bug summary
When the content is being modified in the NestedContentValueConnector it's sent to DefaultValueConnector in Deploy. Deploy is expecting it to be a String but the value for the checkbox is being sent as a Long.
   

`Umbraco.Deploy.Contrib.Connectors.ValueConnectors.NestedContentValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection1 dependencies) :line 97`

![image](https://user-images.githubusercontent.com/42831978/71405458-c943b000-2635-11ea-81be-dbd8b6294a6c.png)

![image](https://user-images.githubusercontent.com/42831978/71405241-1ffcba00-2635-11ea-9bfc-19ba1943c8fd.png)

If I removed the Deploy.Contrib from the project the checkbox was transferred successfully and deploy received the value as a String.

### Specifics
Tested on Cloud with projects running
Umbraco: v8.3.0 and v8.4.0
Deploy: v3.2.0
Deploy.contrib: v3.0.0

Stack trace
```
REMOTE:
System.NotSupportedException: Value of type "System.Int64" is not supported.

   at Umbraco.Deploy.Connectors.ValueConnectors.DefaultValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ValueConnectors\DefaultValueConnector.cs:line 45
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.NestedContentValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies) in C:\UmbracoRepos\Deploy-contrib-3\Umbraco.Deploy.Contrib\src\Umbraco.Deploy.Contrib.Connectors\ValueConnectors\NestedContentValueConnector.cs:line 97
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SerializeNonVariantValue(ICollection`1 dependencies, Dictionary`2 propertyCollection, Property property, IValueConnector valueConnector) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\ContentConnectorBase.cs:line 251
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddProperty(Property property, ICollection`1 dependencies, Boolean published, Dictionary`2 propertyCollection) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\ContentConnectorBase.cs:line 214
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\ContentConnectorBase.cs:line 200
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.MapVersion(IContent content, ICollection`1 dependencies, Boolean published) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\DocumentConnector.cs:line 240
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\DocumentConnector.cs:line 141
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ContentConnector\DocumentConnector.cs:line 102
   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Umbraco.Core.Deploy.IServiceConnector.GetArtifact(Udi udi) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Connectors\ServiceConnectors\ServiceConnectorBaseOfTArtifact.cs:line 49
   at Umbraco.Deploy.Environments.CurrentEnvironment.<GetArtifacts>b__20_0(Udi x) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Environments\CurrentEnvironment.cs:line 310
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreatePackage(Guid sessionId, Manifest manifest) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Environments\CurrentEnvironment.cs:line 600
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass11_0.<BeginCreatePackage>b__0() in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Environments\EnvironmentController.cs:line 126
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<>c__DisplayClass30_0.<ExecuteAction>b__0(CancellationToken token) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Work\WorkItems\SessionWorkItem.cs:line 289
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext() in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Work\WorkItems\SessionWorkItem.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.WaitIdle() in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Work\WorkItems\SessionWorkItem.cs:line 234
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model) in C:\UmbracoRepos\New-Deploy\Umbraco-Deploy\Umbraco.Deploy\Environments\EnvironmentController.cs:line 111
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
```

### Steps to reproduce

1. Create two Doctypes on Live. One that's an element and contains a checkbox property. The other one enabled as Root node. Which contains a nested content property and pick the element with the checkbox.

2. Create a Root node. Then either clone down the project or create a Dev environment. Then try to restore the content to that environment.

### Expected result
Restore the content successfully.

### Actual result
Get an error message saying that a value is not supported.

**Comment by Frost117** [comment] 2020-01-02 10:12
This also has the same behaviour if you are using the Standard Numeric datatype

**Comment by schnitty** [comment] 2020-01-13 11:57
I can confirm that removing the Umbraco.Deploy.Contrib.Connectors.dll is a successful work around for this issue.

**Comment by hfloyd** [comment] 2020-01-14 17:46
Today I experienced the same issue on two 8.4.1 sites - I was unable to Restore content from the cloud to local. Deleting that file and pushing the change to Cloud allowed the Restore to complete.

Does anyone know of any possible ill-effects of removing this file?

**Comment by rensknoors** [comment] 2020-01-15 10:24
I'm also having this issue on 8.4.1. This also happens for document-types nested within a document-type with a nested-content block and checkbox.

Not using the UmbracoDeploy.Contrib package so don't have the .dll either.

**Comment by dpedrovich** [comment] 2020-01-15 11:52
I'm experiencing the same error after upgrading to 8.4.1.
Removing "Umbraco.Deploy.Contrib.Connectors.dll" didn't solve the problem here unfortunately.

**Comment by rensknoors** [comment] 2020-01-15 12:54
> Today I experienced the same issue on two 8.4.1 sites - I was unable to Restore content from the cloud to local. Deleting that file and pushing the change to Cloud allowed the Restore to complete on one of the sites.
> 
> Does anyone know of any possible ill-effects of removing this file?

This is what Umbraco Support told me:

> Nothing unsafe about it apart from not being able to resolve dependencies when deploying the types it handles (nested content and multi url picker)
So what you can do is just remove it while you are doing the transfer from staging to live environment and the re-add it back in again after this.

**Comment by dpedrovich** [comment] 2020-01-15 14:30
I'm experiencing the same issue after upgrading to 8.4.1, and also 8.5.1.

Removing "Umbraco.Deploy.Contrib.Connectors.dll" fixed the problem for me on one of my projects, which made it possible to restore content between DEV/LIVE environment again.
Unfortunately that does not seem to be working for baselines (when trying to restore content on a child project from a baseline).

**Comment by hfloyd** [comment] 2020-01-15 17:08
@dpedrovich The projects I was/am having issues with are also Baseline children, but I wasn't trying to restore from the baseline, but from the child on Cloud to the child locally. 

It's strange to me that this is suddenly happening. I've had these sites up and under very active development for the last few months - lots of baseline dev work pushed to children sites, and lots of work on the children sites locally/on Cloud, restoring and deploying content, from the sites themselves AND from the baseline site.

**Comment by MichaelNielsenDK** [comment] 2020-01-16 07:49
Having the same issue on 8.4.1. 

I tried deleting Umbraco.Deploy.Contrib.Connectors.dll, but that did not help anything, still get the same message when trying to restore.

**Comment by lukehook** [comment] 2020-01-21 11:10
I'm also experiencing this issue - It is making it really difficult to replicate and debug issues on Child baseline sites as we're unable to pull the content from them. The short term fix of removing the Umbraco.Deploy.Contrib.Connectors.dll is not working for me on child sites either. Is there any update on this?

**Comment by clausjensen** [comment] 2020-01-24 10:01
The bug will be fixed in the upcoming 3.3.1 release of Deploy planned to go out on February 4th 2020.
I've however made a nightly available if any of you would like to test it in advance.
There's also a few other nice fixes included for partial restores and a null ref. error when publishing.
[UmbracoDeploy.v3.3.1-alpha-20200124-004.zip](https://github.com/umbraco/Umbraco.Cloud.Issues/files/4107755/UmbracoDeploy.v3.3.1-alpha-20200124-004.zip)

**Closed by clausjensen** 2020-01-24 10:01 UTC

**Comment by dawoe** [comment] 2020-01-27 12:09
I can confirm this fixed the issue

**Comment by clausjensen** [comment] 2020-01-27 13:28
@dawoe Awesome! I'm happy to hear that - and thanks for your response! 😃

**Comment by KasperBHansenAtPentia** [comment] 2020-01-28 15:00
I had some strange behavior using this alpha. I downloaded the .zip and overwrote everything, and tried trasftering from Local to Development

![image](https://user-images.githubusercontent.com/58072872/73275135-f9f3a800-41e6-11ea-8e2a-6abbe8126013.png)

Stacktrace: (Sorry, it's in danish - Error-message translated: Name on remote-unit could not be interpreted: 'development')
48913463 - Executing, 10%
48913463 - Executing, 10% - Get remote session
48913463 - Executing, 80% - Exception!
48913463 - Executing, 80% - Abort remote session
❤
48913463 - Failed, 80% - Total time 00:00:04.583.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.Net.WebException: Navnet på fjernenheden kunne ikke fortolkes.: 'development'
System.Net.Http.HttpRequestException: Der opstod en fejl under afsendelse af anmodningen.
----------------------------------------------------------------

EXCEPTION:

System.Net.Http.HttpRequestException: Der opstod en fejl under afsendelse af anmodningen.
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<BeginSessionAsync>d__27.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<GetSessionOn>d__22.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__16.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

INNER:
  System.Net.WebException: Navnet på fjernenheden kunne ikke fortolkes.: 'development'
     ved System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
     ved System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

**Comment by jmayntzhusen** [comment] 2020-01-28 15:09
@KasperBHansenAtPentia 

Think @clausjensen forgot to mention that you should only copy over the dlls, if you overwrote your config files it won't work. You should restore them from source control but leave the dlls, then it should work for you again 🙂

**Comment by KasperBHansenAtPentia** [comment] 2020-01-28 15:11
Thnaks - Makes sence, since they are 'empty'-isch

**Comment by Emetico** [comment] 2020-01-28 15:28
> @KasperBHansenAtPentia
> 
> Think @clausjensen forgot to mention that you should only copy over the dlls, if you overwrote your config files it won't work. You should restore them from source control but leave the dlls, then it should work for you again 🙂

Hi, i overwrote the dlls and the App_Plugins/Deploy and not the config files. I also tried to remove the Umbraco.Deploy.Contrib.Connectors.dll

But i still get the same error.

Do i need to remove from the environment i try to restore from also?

**Comment by KasperBHansenAtPentia** [comment] 2020-01-28 15:35
I also ran into a new issue

The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API has thrown an exception. It might have been caused by an inner System.NotSupportedException with message: Invalid prefix 'l', when trying to parse 'l1'.

The following artifacts might be involved:

umb://document/bac5262e745d4809b00f1322408f22ed

**Comment by clausjensen** [comment] 2020-01-28 15:39
@Emetico You need to upgrade all environments where you expect this to work. So yes - update and make sure to push through to all your environments.

@KasperBHansenAtPentia same to you. Make sure to upgrade all environments before attempting to transfer content.

**Comment by clausjensen** [comment] 2020-01-28 15:42
And just for the record - noone needs to (and noone should!!!) remove the Contrib .dll from their sites.

It is **not** a fix and it is **not broken**. The only thing you achieve by doing this is that nested content is no longer handled correctly.... which essentially yes - makes a transfer "work"... but only because it really no longer handles the data it is transferring.

**Comment by Emetico** [comment] 2020-01-29 07:58
> @Emetico You need to upgrade all environments where you expect this to work. So yes - update and make sure to push through to all your environments.
> 

After i upgraded environments affected, it worked like a charm.

Thank you Claus.

**Comment by clausjensen** [comment] 2020-01-29 08:17
@Emetico No problem! Great to hear it works for you as well 😃

**Comment by lukehook** [comment] 2020-01-29 10:50
@clausjensen I've implemented the DLL's and pushed to all environments. This fixes full restore (YAY!) but when I do a partial restore and click to pick content I know see the following 404 error.

![image](https://user-images.githubusercontent.com/7995797/73350538-21994d80-4285-11ea-88e2-b337b64aa49b.png)

Am I missing something?

**Comment by clausjensen** [comment] 2020-01-29 12:20
Looks like some javascript files are cached. Try cachebusting the ClientDependency cache by updating the version in the client dependency config file. Or alternatively (in order to debug if this is the issue) try running your site in debug mode - then it should not use cached files.

(Oh - and of course clear all browser caches while testing these things)

**Comment by lukehook** [comment] 2020-01-29 12:42
@clausjensen I'll test that now. Should I have updated the JS files then? I made sure just to copy over the DLL's as per instructions above

**Comment by clausjensen** [comment] 2020-01-29 13:22
Ah - I did not see that @jmayntzhusen mentioned only the dll's. You should definitely copy over everything _except_ the config files. The error you are seeing is because the endpoint the JS files are attempting to contact, was renamed.

**Comment by ronaldbarendse** [comment] 2020-03-27 09:42
I'm also having a lot of problems with the `Umbraco.Deploy.Contrib` assembly that's now apparently shipped by default on Umbraco Cloud. The following exception was getting thrown when trying to restore content from Live to local:

```
System.NotSupportedException: Invalid prefix '[', when trying to parse '[{"name":"Sortiment","udi":"umb://document/1bb7320de61941e5ad803d679c247be7"}]'.
     at Umbraco.Deploy.Connectors.ValueConnectors.DefaultValueConnector.FromArtifact(String value, PropertyType propertyType, Object currentValue)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SetVariantPropertyValue(IDictionary`2 artifactPropertyValues, Property currentProperty, PropertyType propertyType, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.UpdatePropertyType(TContent content, IDictionary`2 artifactProperties, Boolean currentContentIsPublished, PropertyType propertyType, IEnumerable`1 cultures)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapContentProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artifactProperties, Boolean currentContentIsPublished)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process4(DeployState state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
     at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
```

After removing `Umbraco.Deploy.Contrib.Connectors.dll` from the Live environment, it successfully restored the content. The property data in the exception is an `Umbraco.MultiUrlPicker` data type (directly on the document type), which is a default Umbraco data editor. The contrib assembly seems to ship a custom value connector for this type, which seems odd, as it should be included in the base `UmbracoDeploy` package, right?

Could this be caused by the fact that `UmbracoDeploy.Contrib` is not installed locally, so the local environment doesn't support the artifact data returned by the custom value connector from the contrib assembly?

**Comment by nul800sebastiaan** [comment] 2020-03-27 09:50
@ronaldbarendse AFAIK we've always shipped with that dll. We made it a separate project so we could open source it and people could learn from that to make their own connectors for their custom property editors. If it's not committed to your git repository then you should definitely add it, on all environment.

**Comment by clausjensen** [comment] 2020-03-27 12:58
@ronaldbarendse as @nul800sebastiaan mentions, Contrib has always been part of Cloud (as separate dll as well). It however wasn't added in the first while for Deploy targetted for V8 (by mistake - it was an oversight).
The result of this being that many of the things that were working in Deploy on V7 simply wasn't being "handled" in V8 sites. While deployments were actually going through without any apparent errors, many of the transformations and dependency resolving action simply weren't happening... so while it seemed like things were working fine - anything other than "simple data" wasn't really being transferred correctly.

When the Contrib dll was then added in, things started to work... or.. well.. fail 😄 .. depending on how you look at it. So while it was a step in the right direction to add the Contrib dll for V8, it has also caused a bunch of issues to now bubble up to the surface as actual errors being thrown.

The good thing about all this is that we are now becoming aware of what actually doesn't work and that means we can work on fixing it. The most important thing however to understand is that removing the Contrib dll is not what should be considered a good fix as many other things will not work and doing it is really just hiding errors.

If you are still experiencing issues with the Contrib dll in your site, I would however encourage you to make sure they're reported. Then we'll do what we can to pick them up and get them fixed. There's unfortunately so many different ways to use Umbraco and build up document types - and much of this has been changing just slightly in format from V7 to V8 - so much of this will have to be found along the way as people use it.

**Comment by ronaldbarendse** [comment] 2020-04-21 07:57
> Could this be caused by the fact that `UmbracoDeploy.Contrib` is not installed locally, so the local environment doesn't support the artifact data returned by the custom value connector from the contrib assembly?

To answer my own question: this was indeed the real problem. After installing `UmbracoDeploy.Contrib` locally and ensuring it was also present on the production/live environment, I've not encountered the error...

@clausjensen If that's the case, why isn't Umbraco Deploy updated to include the fixes for these Umbraco core editors (Nested Content and Multi URL Picker)? I would expect the Contrib package to only add additional support for 3rd party editors, but none have been added so far...

**Comment by clausjensen** [comment] 2020-05-19 09:19
@ronaldbarendse Due to limitations in what is open and closed source, we're a bit limited on our options. We have Deploy which is closed source - and we have Deploy.Contrib which is open source and available for anyone to contribute to.

From a product perspective it makes perfect sense to put the Nested Content connector in the closed source Deploy project, as Nested Content itself is included as a part of the CMS. It also makes perfect sense that Deploy.Contrib then only contains connectors for 3rd party libraries that are not part of the standard CMS (only for 3rd party packages really).

Doing this however has the downside that no one apart from HQ would be able to debug/bugfix anything on these connectors as the code isn't public. Due to that - we decided that some things that has started out as community projects, may be better off living in the Contrib repository where the people who initially created them and know them best, can still contribute to the connectors.

Regarding there being no 3rd party connectors in Contrib - that is only for version 3.x of contrib because none have been added yet. Version 2.x (which targets Umbraco CMS 7) contains plenty of 3rd party connectors:
https://github.com/umbraco/Umbraco.Deploy.Contrib/tree/dev/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors

**Comment by ronaldbarendse** [comment] 2020-05-19 10:12
@clausjensen Seems like a reasonable decision... I would however recommend making `UmbracoDeploy.Contrib` a dependency of `UmbracoDeploy` if it's actually required to ensure core editors work/deploy correctly 😉

**Comment by clausjensen** [comment] 2020-05-19 10:21
@ronaldbarendse It could prolly be a Nuget dependency .. I'm not sure how that works with circular dependencies. Deploy is a dependency of Deploy.Contrib and it has to be.

We're however talking about what other options we have .. one could be to go with 3 repos. One for the Deploy Core (closed) and one for the parts we want available as open source - and then the third one for 3rd party libraries. No decision made there yet though as this will have a bunch of other implications as well to consider... but we'll see what we end up with 😄

**Comment by cb-tomsearle** [comment] 2020-06-04 09:50
Adding the UmbracoDeploy.Contrib (not Umbraco.Deploy.Contrib) package fixed this issue for me. Just make sure to turn off dependency handling in Visual Studio as it won't be able to find the UmbracoDeploy NuGet package.

**Comment by ronaldbarendse** [comment] 2020-06-05 07:36
@cb-tomsearle You can install `UmbracoDeploy` (and `UmbracoDeploy.Forms` if you also have Forms installed) from MyGet by adding the following NuGet source: https://www.myget.org/F/uaas/api/v3/index.json.

This is also used in UmbracoDeploy.Contrib: https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/67ffd2d0289af2823ea9292813b990e5813feb49/src/NuGet.config#L5). @nul800sebastiaan @clausjensen When will these packages be pushed to NuGet.org, so we don't have to add this custom feed? 😉
