### ISSUE TITLE
Umbraco Cloud: Logout after 1 hour

### ISSUE THREAD

**Issue by reneemhaas-diagram** [umbraco/Umbraco.Cloud.Issues#565] opened 2022-03-16 18:24 UTC
### Issue description

While actively working in Umbraco Cloud (clicking around, replying to change, deploying code) we are logged out of the Umbraco Cloud S1 portal.

This is a problem for us particularly as we have 35 child sites so deployments often take longer than an hour, and we are booted out in the middle of deployments.

**Comment by sajumb** [comment] 2022-03-18 07:13
Hi @reneemhaas-diagram ,
This is obvious not the experience that we want you to have. We have tried to reproduce this error but without any luck. Also I have reached out to support and asked if this was a known phenomenal but this seem to be an isolated issue.

Could the enforced logout somehow be related to a security setting or software running on your side?
Will it be possible for you to record the network traffic in the browser's developer tools and upload it here or send it to me?

**Comment by c9mbundy** [comment] 2022-03-18 08:22
I can confirm the existence of this behavior, but have no firm details to identify the cause. To date, I've just treated it as an annoyance but assumed it was a known issue that was still unresolved. I typically seem to encounter it when using multiple tabs for doing baseline deployments to multiple child-sites, and would normally have at least 2 browser tabs open - one for the baseline-master and another for at least one baseline-child. However, I've also encountered situations while generally working in the portal for a while, and  have a short period of inactivity - needing to do something else for few minutes - only to find I've been logged out when I return to the portal tab.

**Comment by RyuLindow** [comment] 2022-03-18 08:35
@sajumb 

It's UmbracoId logging you out and does happen often.

**Comment by reneemhaas-diagram** [comment] 2022-03-18 13:49
Similar to what c9mbundy, I also experience it most with when using multiple tabs for doing baseline deployments to multiple child-sites.

**Comment by NikRimington** [comment] 2022-03-18 13:59
Does it log you out of both sites, or just one? It could be conflicting cookies if the urls are different between the sites? It could be worth, if you can reliably replicate the issue, have Dev Tools open for each active tab so you can monitor the network traffic to see if that shows something

**Comment by reneemhaas-diagram** [comment] 2022-03-18 14:02
Log you out of both sites? Its logs out of all tabs that have the Umbraco S1 Cloud/Portal open.

**Comment by RyuLindow** [comment] 2022-03-18 16:11
It should log you on all tabs, as that technically counts as one UmbracoId session.

**Comment by sajumb** [comment] 2022-03-21 08:30
We will create a ticket for this and look into it. If you by chance can record network traffic as the issue occur please provide it in this thread or send it to me directly. We will try to reproduce the issue and keep you updated here.

**Comment by sajumb** [comment] 2022-05-03 06:19
Hi, we have tweaked various settings meaning that you should not be logged out of the portal or the backoffice in Umbraco cloud for a period of six hours. Sorry for the long wait of this improvement. Let me know if you find any issues. If not, we will close this thread in a week from now.

**Closed** 2022-07-08 06:48 UTC
Labels: category/portal

**Comment by reneemhaas-diagram** [comment] 2022-08-02 15:13
I am still seeing being logged out of https://www.s1.umbraco.io/projects after an hour.

**Comment by sajumb** [comment] 2022-08-03 11:01
Hi @reneemhaas-diagram,
Thanks for the report. We will look into this.

**Comment by sajumb** [comment] 2022-08-05 10:56
I have tried to reproduce this myself with three different users on various machines. I have not been able to reproduce or found any recently code changes that could cause a premature logout.

Do you perhaps use a user account that is shared with one or more people? If e.g. one of your colleagues logout the same cloud user account that you are using that would impact your session as well.

**Comment by reneemhaas-diagram** [comment] 2022-08-05 13:35
Yes, although this has occurred with just myself logged in.
