### ISSUE TITLE
Issue with cache after pushing code to live

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#223] opened 2020-06-08 12:35 UTC
This issue could be related to:
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/186

I often have a issue after pushing code changes to live that I loose pages from cache. I can't pinpoint what triggers this and I can't find a pattern.

This has been happening since the start of V8 where the issue in V8.0.x was happening almost every time and in later versions it seems more random.

My workflow now is as follows:
- push to live
- login to umbraco 
- reload memory cache

Wile this is a consistent fix and no issues happened since I use this workflow it is error prone (I forget to reload sometimes and if someone else picks up a issue they have to know about this workflow).

Since it is a basic workflow I was wondering if we can reload cache after pushing code and maybe content automatically.

If more info is needed I'm willing to test some scenarios

**Comment by nul800sebastiaan** [comment] 2020-06-10 06:40
@FransdeJong Do you have the same error listed as in #186? If so, it would be good if you could find any Tags datatype that might be involved in the content you're transferring and seeing what the value is. It might be that something unexpected is stored in the json field?

**Comment by FransdeJong** [comment] 2020-06-10 06:48
No, I get no errors at all. Only the message that the node is published but not visible on the info tab where normaly the URL should be.

I'm also not talking about content transfer but pushing code to another environment.

The reason I linked the issue is that it seems the new cache introduced in V8 doesn't like updates without reloading. At least in my case reloading is enough.

**Comment by FransdeJong** [comment] 2020-07-14 08:05
It happened again today. Two pages were dropped from cache after pushing code from stage to live.
This is a serious issue because random pages are disappearing and there is no way to check this. The update only contained a view this time.

After I reloaded cache it all worked again. I strongly suggest that a cache reload is forced after every push of code since this solves the issue and relying on me (a human) to push the button every time after I push a file is error prone...

**Comment by jmayntzhusen** [comment] 2020-07-14 08:20
What modelsbuilder mode are you using? 

Have recently discovered some issues with using MB on dll mode where the dll is not committed when changes are made, since the cache is based on the models when you then push updated uda files to an environment but not the updated models you will get this problem as the uda file extraction will update the properties in the db but the models are still the old models until you either push up the updated models dll or rebuild the models from the backoffice.

I will write up some docs on how to work with MB on Cloud to avoid this.

**Comment by FransdeJong** [comment] 2020-07-14 08:23
I'm using MB Api. The only thing I pushed in this case is a partial view. No changes made to anything else.
It looks like the two latest published content nodes were dropped after I pushed the view.

**Comment by jmayntzhusen** [comment] 2020-07-14 08:30
Alright, sounds like a separate issue then, thought I would check 🙂

**Comment by FransdeJong** [comment] 2020-07-14 08:36
I'm all for checking every angle. 👍

**Comment by skttl** [comment] 2020-12-11 08:12
We are hitting issues similar to this.

We mostly see it when creating content in local, and pushing that to staging.

Afterwards, that content sometimes dissapear from the cache, when pushing new code to the project. This is in 8.9.0.

We've also seen something similar on 8.6.6 in another project.

**Comment by hfloyd** [comment] 2021-05-12 15:39
I  have been noticing a similar issue on one Cloud project in particular - a code push (via the Cloud Portal to LIVE environment) happens without any errors reported, but now pages are missing from the live site front-end (like the Nav menu is almost empty, random links are 404-ing, etc). Refreshing the Memory Cache via the back-office "Settings" section brings everything back. I've also noticed that the Examine index is also getting corrupted or truncated or something, and I need to do a re-index on that as well via the back-office button.

**Comment by FransdeJong** [comment] 2021-05-18 07:56
A simple solution would be to trigger a cache reload after pushing anthing to a environment?
Just thinking out loud...

**Comment by FransdeJong** [comment] 2021-09-16 11:34
What is the status of this issue?
Today I had a call again from a customer that noticed some pages that didn't work after a update...

I would strongly advice to always reload the cache after a deploy action. @AndyButland is it possible to do something like this?

**Comment by FransdeJong** [comment] 2022-01-31 07:58
This issue is still happening at least on Umbraco V8.
@AndyButland is it possible to reload memory cache after each deploy? This seems like the best solution for now since there is no way to pinpoint the random(?) cause of this issue.

I hate the fact that a client has to call us if a developer forgets to reload cache after deploying to live. It's a unnecessary error-prone manual step.

**Comment by AndyButland** [comment] 2022-01-31 11:05
It's not straightforward to do that I think, at least from Deploy itself - in the sense that reading up this issue it seems the original time it was raised and in some of the further comments, this has happened with code updates.  Umbraco Deploy as a component, is only triggered in the situations where there are schema updates in a Cloud deployment.  So if it is needed on any code deployment, that would need something working between the Cloud deployment script and the CMS.

I was under the impression though that, at least under the new infrastructure, a deployment triggers a recycle - evidenced by the `Triggering recycle (preview mode disabled)` message in the logs.  Which I would have thought would have cleared and reloaded the memory cache anyway.  But if you say it's still happening on projects migrated to the new infrastructure, I guess either that can't be sufficient, or there's an intermittent CMS issue where this cache isn't populated correctly after a recycle.

**Comment by FransdeJong** [comment] 2022-01-31 12:09
We've seen this happen when pushing code, pushing schema data or a combination.
The moment i'd like to see a cache reload is after copying the files from the repo to the environment.
I don't know if deploy is the correct place but if the reload could be triggered after copying/after deploy that would be great. This will make sure issues like this don't happen anymore.

**Comment by ronaldbarendse** [comment] 2022-04-05 07:30
We have spotted and fixed an issue in the CMS that sometimes causes content to disappear from NuCache after a document type is changed, see: https://github.com/umbraco/Umbraco-CMS/issues/12110.

Both the cause (a deployment changing document types) and the result (contents disappearing) seem to match the reproduction steps, so I'd highly recommend users that have this issue to upgrade to 8.18.3 and 9.5.0 when those get released!

**Comment by sajumb** [comment] 2022-05-02 11:27
Due to the fix in 8.18.3 and 9.5.0 and the potential workaround by enabling the automatic reload of memory cache following disk read operation in Umbraco Deploy, we will close this issue.

**Closed by sajumb** 2022-05-02 11:27 UTC
Labels: category/umbraco-deploy, category/portal, state/needs-more-info
