### ISSUE TITLE
Restore fails after upgrade to Umbraco 8.14.0

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#405] opened 2021-06-17 10:58 UTC
### Issue description

After upgrading an Umbraco Cloud project from v8.6.4 to v8.14.0 the restore fails, because of changes in a few datatype configurations.

- Media Picker (obsolete)
- Upload
- True/false

![image](https://user-images.githubusercontent.com/2919859/122382817-8e8cb080-cf6a-11eb-9cab-6c7603a45156.png)

I solved the issue by re-saving these datatype on the remote environment, but it seems is failed because of mismatch in schema.

**Media Picker** (obsolete) has a new configuration property "notice":

![image](https://user-images.githubusercontent.com/2919859/122383364-0bb82580-cf6b-11eb-8f06-35ed6f679283.png)

**Upload** has a new configuration property "fileExtensions":

![image](https://user-images.githubusercontent.com/2919859/122383279-f8a55580-cf6a-11eb-88ad-48ebe214f38b.png)

**True/false** has a few new configuration properties, but I think these was added pre v8.14.0

![image](https://user-images.githubusercontent.com/2919859/122383737-60f43700-cf6b-11eb-96f2-26fef9fd88f6.png)

I think this may be an issue in Umbraco Deploy which in unable to restore with these mismatches (it seems it expect these properties to be available and failed when they were not available).

---
_This item has been added to our backlog [AB#12904](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12904)_

**Comment by AndyButland** [comment] 2021-07-07 09:34
I've been investigating this, and perhaps mostly for reference myself for future, will document what's happening here:

- Deploy determines all the dependencies for the full restore operation, which includes all data types used by all content being restored.
- It builds up a `Manifest` containing an entry for each UDI that needs to be restored (all marked with a mode of `Deploy`, indicating that they need to be transferred).
    - When restoring the "Source" is the _upstream_ environment.
    - Each entry has a `CheckSum` that has been populated from the signature of each artifact in the upstream environment.  This is retrieved from a database cached signature for the artifact, if it's available.  If the database record is not found, it's generated by retrieving the artifact via the appropriate connector.
	    - So this is why, after an upgrade that has changed something that will affect in a particular artifact's serialized representation - e.g. a new configuration field in a data type as we have in this issue - we get back an out of date representation of the entity from the database cache.
	    - See `TargetRestoreWorkItem.Proceed()` and the call to `CreateManifestOnSource()`.	
- The manifest is then reviewed.
    - Local signatures are retrieved, again either from the cached database records, or for missing ones by retrieving the artifacts via the appropriate connector.
	- For a fresh restore - or just if the data type has never been saved locally - there will be no cached signature, and hence they will be retrieved from the connector/artifact meaning locally we have an up-to-date representation.
	- Each deployable UDI in the manifest is checked comparing it's local and remote signature.  For those that are the same, the mode for entry in the manifest is updated from `Deploy` to `Skip` (indicating that we already know about it locally, and there's no need to transfer it)  Where we have aa difference between the local up-to-date representation and the remote cached one, the entity remains marked as one we need to deploy.
	    - See `TargetRestoreWorkItem.Proceed()` and the call to `NegotiateManifest()`, which calls into `CurrentEnvironment.ReviewManifest()`
- We then validate the manifest to check for any items that are marked for deployment but aren't of entity types that are configured to be transferred via a restore operation.  Data types are not configured to be restored in this way (we expect them to be transferred "as schema" via source control).
    - As we have a data type in this state, the mismatch is reported.
	    - See `TargetRestoreWorkItem.Proceed()` and the call to `ValidateManifest()`
---

To resolve, as noted in the original issue report, you can handle them one at a time by resaving the items in the upstream environment.  Doing this will update the cached signature to the new representation and ensure we get a matching check sum in the validation described above.

Or you can trigger a "Clear Signatures" operation in the upstream environment - either via a marker file on disk, or, more easily, via _Settings > Deploy > Deploy Operations > Clear Cached Signatures_ and click _Trigger Operation_.

![image](https://user-images.githubusercontent.com/1993459/124733487-88a84080-df14-11eb-881d-d49e337d377f.png)

---

For Deploy 4.2.0, we have added a "clear signatures" step as a migration, when Deploy updates to 4.2, signatures will be cleared and hence any changes to artifact representations caused by other features in the release will not cause similar errors.

We need to consider if we could do something similar for CMS minor releases, which would avoid having to ask the implementor to carry out the step via the back-office as described above.  That's trickier though, as the clear signatures operation is in Deploy,, not in the CMS.

**Comment by warrenbuckley** [comment] 2021-07-21 08:28
Fixed by PR https://github.com/umbraco/Umbraco-Deploy/pull/568 and due for Deploy 4.2.0

**Closed by warrenbuckley** 2021-07-21 08:28 UTC
Labels: category/umbraco-deploy, state/sprint-candidate
