### ISSUE TITLE
Subscription Upgrade Flow: Inability to upgrade project from trial to starter, after dismissing notification.

### ISSUE THREAD

**Issue by MahmoudUmbraco** [umbraco/Umbraco.Cloud.Issues#97] opened 2019-07-22 07:53 UTC
Hi team,

We would like to have an upgrade button in the portal view for trial projects. 
Today the user has to add "/paymentmethod" in the URL of the portal view in order to be able to upgrade a trial project to a starter plan. 

All the best
/ Mahmoud - Swat

**Comment by pijemcolu** [comment] 2019-07-22 08:05
Is this functionality on the project page the same? 

![image](https://user-images.githubusercontent.com/11557946/61616228-35c21980-ac68-11e9-9d09-f255a63ca2ae.png)

**Comment by MahmoudUmbraco** [comment] 2019-07-22 09:33
Hi @pijemcolu 

Yes, that button is not showing anymore.

**Comment by pijemcolu** [comment] 2019-07-22 12:41
The problem is that you can click and discard the notification: which leaves you in a state where you can't upgrade to a starter from a trial project unless your project has expired.

In order to fix the issue which is: inability to upgrade project from trial to starter, I'd propose a change to the side menu, where `Upgrade to Pro plan` changes according to which plan the user is currently on. Trial -> starter. Starter -> Pro Plan.


![image](https://user-images.githubusercontent.com/11557946/61633126-b0059480-ac8e-11e9-97ac-3dd6a5a30133.png)

**Comment by MahmoudUmbraco** [comment] 2019-07-23 09:44
It would be awesome if you could change it according to which plan the user is currently on 👌

#H5YR

**Comment by jmayntzhusen** [comment] 2020-01-03 10:32
This should no longer be an issue as it just says upgrade plan now and leads to a new page where you select the plan. Closing..

**Closed by jmayntzhusen** 2020-01-03 10:32 UTC
