### ISSUE TITLE
Deleting a document type doesn't remove dependencies from its dependents.

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#66] opened 2019-03-27 08:04 UTC
Just had an issue where I got at deploy-failed marker after deleting a doctype. Turns out, if you have a doctype (B) allowed as a child of doctype (A), if you delete B, then the uda file of A isn't updated, and still depends on B, who now doesn't exist. And when another environment tries to deploy, you get an error.

```
{
  "Date": "2019-03-27T08:58:09.1204897+01:00",
  "Message": "Could not get content type with id 48b50e8b-f176-4808-afc6-3ae17dd8a94f.",
  "Ex": {
    "ClassName": "Umbraco.Deploy.Exceptions.EnvironmentException",
    "Message": "Could not get content type with id 48b50e8b-f176-4808-afc6-3ae17dd8a94f.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   ved Umbraco.Deploy.ServiceConnectors.ContentTypeConnectorBase`2.<>c__DisplayClass17_0.<Pass2>b__0(GuidUdi x)\r\n   ved System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n   ved System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   ved System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   ved Umbraco.Deploy.ServiceConnectors.ContentTypeConnectorBase`2.Pass2(DeployState state)\r\n   ved Umbraco.Deploy.ServiceConnectors.DocumentTypeConnector.Pass2(DeployState state)\r\n   ved Umbraco.Deploy.ServiceConnectors.ContentTypeConnectorBase`2.Process(DeployState state, IDeployContext context, Int32 pass)\r\n   ved Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)\r\n   ved Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\n<Pass2>b__0\nUmbraco.Deploy, Version=2.0.15.0, Culture=neutral, PublicKeyToken=null\nUmbraco.Deploy.ServiceConnectors.ContentTypeConnectorBase`2+<>c__DisplayClass17_0\nUmbraco.Core.Models.ContentTypeSort <Pass2>b__0(Umbraco.Core.GuidUdi)",
    "HResult": -2146233088,
    "Source": "Umbraco.Deploy",
    "WatsonBuckets": null
  },
  "Sender": "Umbraco.Deploy.WorkItems.DiskReadWorkItem"
}
```

To reproduce:

Add a new doctype (B):
![billede](https://user-images.githubusercontent.com/3726467/55059232-bc763980-506e-11e9-870f-031818725aa8.png)

Allow it as child of another doctype (A):
![billede](https://user-images.githubusercontent.com/3726467/55059265-cd26af80-506e-11e9-8e97-eee6e57a99b3.png)

Delete the new doctype (B)
![billede](https://user-images.githubusercontent.com/3726467/55059300-dfa0e900-506e-11e9-91c4-eda6e17db615.png)
Note, it only removes its own uda file.

Pull the changes to another environment, and do a new deploy (echo > deploy). The deployment will fail.

If you do it on the same environment where you did you changes, it will work. It's only when you pull those changes to another environment, that you get into trouble.

**Comment by ronaldbarendse** [comment] 2019-03-27 13:40
This seems to be related to https://github.com/umbraco/Umbraco.Cloud.Issues/issues/17, so resaving dcoument type A should update/remove the dependency on B. Running a `deploy-export` might also work, as that updates all UDA files.

**Comment by clausjensen** [comment] 2019-04-02 06:27
@ronaldbarendse running the `deploy-export` will not fix the issue, as it basically just loops through every entity in the system, exporting it to UDA file, in the state that it is currently in.

The fact is that the doctypes having the dependency to the deleted one, will actually be in a broken state, until they are manually loaded up in the UI and resaved. Unfortunately (as we don't have a system for doing reverse lookup of dependencies) updating all other entities to be in a correct state after a delete, would require us to loop through every single document type whenever a delete is done, and ensure that if it was using what is now deleted - this dependency is now removed and the document type is resaved. It is also not enough to just resave the doctypes via the API - they would either need to be loaded in the UI (so the *UI* fixes the error by removing the allowed child doctype) and saved ... or you would have to load it via the API - remove the allowed type and then save it.

As @ronaldbarendse mentions however - you can manually fix this by simply resaving the document type which had the deleted doctype as an allowed child. This will ensure the UDA file is updated.

I think what has prevented us from picking up this task so far is that doing this automatically, would require that we have a way of temporarily disabling these event hooks in Deploy - otherwise we'd be starting yet another loop of everything, every time we find a doctype that needs to be updated and saved again.

**Comment by ronaldbarendse** [comment] 2019-04-02 07:59
So the real bug is actually within Umbraco itself, as it doesn't properly update the dependencies 😉 And the error Deploy gives is just an indication of that (so other deploy systems, like uSync, probably also have this issue).

Although the UI automatically fixes this issue, because it can't load the deleted depencency and silently lets you re-save/overwrite the corrupt state, manually updating should be possible, right? It would indeed require loading all document types, but only save when the deleted dependency is removed from it... I'm not sure how this could result in a loop though; what would cause that to happen?

**Comment by clausjensen** [comment] 2019-04-02 08:21
@ronaldbarendse very true :) and if we had some sort of dependency tracking in Core, this would be so much easier to implement. uSync should have the same problem unless it does some ninja tricks to avoid it. I guess you could maybe get away with ignoring this dependency .... and maybe you could also take into account when generating the schema files - that if an allowed child doc type is not available - it is simply kept out of the artifact generation and checksums.

It is however not really a pretty way to do it, as you would then have actual entities in the system that doesn't correspond to the artifacts being generated - and we really don't want to start doing that.

Regarding the updating - yes. What happens is that the UI "fixes" it for you by not being able to load the missing data .. and then the state you're resaving is actually now valid.
And yep - manually updating is indeed possible.

Regarding the loop - I think I was a little tired yesterday - there's no loop happening really... I was thinking that resaving the other doctypes would trigger another round of "is this used by any other doctype"-checking. But since that's only on deletes and not on saves, everything should be good actually - and no loops should be happening 😄  Sorry about that!

**Comment by clausjensen** [comment] 2019-04-02 08:24
The good thing here though is that... if someone were to actually do a PR for Core that basically:
- Loops through all the other existing doctypes on a doctype-delete
- Checks whether this particular doctype is used as an allowed child doctype
- Remove it from the allowed child doctypes
- Save the doctype in its new correct valid state

Then Deploy should actually just generate the artifacts as well and I think the problem should be solved.

**Comment by tormnator** [comment] 2020-01-06 20:23
Just got bit by this in Umbraco 7 Cloud after pushing changes from Local to Dev. Until the issue is fixed could someone in the doc team please update https://our.umbraco.com/Documentation/Umbraco-Cloud/Troubleshooting/troubleshooting-portal with instructions on how to solve the problem (e.g. make a temporary change to the document type, save, remove the temporary change, and save again). Also, that doc page should include instructions on how to find a document type based on its UDI. I'm not sure of a way to do that in the back office, I looked in the /data/revision folder for the file name containing the UDI.

**Comment by jmayntzhusen** [comment] 2020-01-07 08:36
@tormnator 

In Umbraco 8 you can search on a guid in the search and it will find doc types, data types, etc. In Umbraco 7 checking the udi files or the database is the only way.. If you have a specific Deploy error that gave you a guid and not a name then you can create an issue on it and we may be able to pass along the name in the error message as well.

As for documentation updates it would be nice, can you make an issue on the [documentation tracker](https://github.com/umbraco/UmbracoDocs/issues) so they are aware of this?

**Comment by tormnator** [comment] 2020-01-07 16:46
@jmayntzhusen  This very issue/deploy error ("Could not get content type with id") lists UDI's (guids), and no names or "old type" Id's. It's been a while since last time I experienced the other "well known" data extraction errors, but in my experience they all reference Udi's and no names/id's.

[I created a documentation issue :-)](https://github.com/umbraco/UmbracoDocs/issues/2177)

**Comment by jmayntzhusen** [comment] 2020-01-08 08:53
@tormnator 

Unfortunately that specific error "Could not get content type with id" is not something we can change without a lot of rework, here is why:

If you take a UDA file it may look something like this:
```
{
  "DefaultTemplate": null,
  "AllowedTemplates": [],
  "Icon": "icon-article color-black",
  "Thumbnail": "folder.png",
  "Description": null,
  "AllowedAtRoot": false,
  "IsContainer": true,
  "Parent": "umb://document-type-container/3cebf62fe96844e3abc93a429244a086",
  "AllowedChildContentTypes": [
    "umb://document-type/c7c66f04793e459bb6d2ba5195fc6db7"
  ],
  "CompositionContentTypes": [
    "umb://document-type/e63331f2a2374e1898ee61941a6e6186"
  ],
  "PropertyGroups": [],
  "PropertyTypes": [],
  "Udi": "umb://document-type/5230da699dc14667a982428ade2af3f0",
  "Dependencies": [
    {
      "Udi": "umb://document-type/c7c66f04793e459bb6d2ba5195fc6db7",
      "Ordering": false,
      "Mode": 0
    },
    {
      "Udi": "umb://document-type/e63331f2a2374e1898ee61941a6e6186",
      "Ordering": true,
      "Mode": 0
    },
    {
      "Udi": "umb://document-type-container/3cebf62fe96844e3abc93a429244a086",
      "Ordering": true,
      "Mode": 0
    }
  ],
  "Name": "Blogs",
  "Alias": "Blogs",
  "__type": "Umbraco.Deploy,Umbraco.Deploy.Artifacts.DocumentTypeArtifact",
  "__version": "2.0.15"
}
```

This error is when it loops through things like `CompositionContentTypes` & `AllowedChildContentTypes` to add dependencies, which means all we have is the udi at that point, and since we can't find it we don't know anything else about it.. 

What we could do is change the error message to something like
```
"Could not get document type with id " + x.Guid + " which is an allowed child document type of " + parent.Name
```

Since this is an operation run from the parent in the first place we can add info on that and how it is linked to this other entity we can't find. Would that help at all?

**Comment by tormnator** [comment] 2020-01-08 17:12
Yes, that would be very helpful.

"Could not get" is a bit vague, maybe something like this:

> "Document type {x.Guid} not found! This document type is listed as an allowed child content type of parent document type {parent.Name} ({parent.Id} / {parent.Guid})."

**Comment by clausjensen** [comment] 2020-11-19 13:26
This has been fixed in the CMS by sending an updated event for the allowed child document types when they are updated.
See: https://github.com/umbraco/Umbraco-CMS/issues/8256

**Closed by clausjensen** 2020-11-19 13:26 UTC
Labels: category/umbraco-deploy, state/needs-investigation, type/feature
