### ISSUE TITLE
DocType Grid Editor Dropdown selection not resolving

### ISSUE THREAD

**Issue by jmenendezFKQ** [umbraco/Umbraco.Cloud.Issues#91] opened 2019-06-24 16:00 UTC
When deploying content using the DocType Grid editor, with a DocType using the following properties:

alias: image type: Umbraco.MediaPicker2 *Madatory
alias: style type: Umbraco.Dropdown.Flexible (with 3 prevalues) *Mandatory

When deploying, the selected prevalue does not get pushed to the target environment,

Steps to reproduce

1. Create a DocType using the above listed properties
2. Push changes to dev via git
2. Add the DocType to the grid using DocType grid editor.
3. Push content to Dev environment using Umbraco Deploy.

Expected:
The image is pushed and the selected dropdown value should be retained.

Actual Result:
The image is retained the style selection is not retained.

**Comment by jmenendezFKQ** [comment] 2019-09-30 14:28
This issue has been open for 60 days, is there any one who may have a resolution to this?

**Comment by jmenendezFKQ** [comment] 2019-10-08 15:55
Can anyone please assist with this issue?

**Comment by jmenendezFKQ** [comment] 2019-10-09 19:41
Hey nul800sebastiaan,

Thanks for your reply.

I guess I should have put in my original post that we are on Umbraco 7.14.1 which does use the Umbraco.Dropdown.Flexible property editor https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/DropDown/index-v7

With that being said, our project is also on the Umbraco Cloud which, by default uses the Deploy Contrib library for version 7. The following file is currently in my project and has been since the project inception when we created the Cloud website:

Umbraco.Deploy.Contrib.Connectors.dll here is the file info for it:

![Capture](https://user-images.githubusercontent.com/11065732/66514454-27d3a600-eaab-11e9-8fde-3c3f41b140c3.PNG)

Let me know if this changes anything.

**Comment by nul800sebastiaan** [comment] 2019-10-10 10:04
Ah great! I couldn't tell if it was a v7 or v8 version indeed. That is the latest version you've got there.

We'll need to have a look at it, but maybe it would be possible for you to debug using the source of the Deploy Contrib project before we can get to it. It's open for contributions and if you know where the bug is, that would be very helpful.

**Comment by clausjensen** [comment] 2019-10-11 21:39
@jmenendezFKQ I've looked into the issue and it turned out to be a rabbithole of bugs in various prevalue related code - not just this issue. I think I've got it all fixed up now but it will need some testing and reviewing as it required changes in both Deploy.Contrib and Deploy itself.

I can't give you an exact timeframe on when it will be merged and released, but at least you know a fix is on the way.

**Comment by clausjensen** [comment] 2019-10-11 22:26
@jmenendezFKQ If you would be willing to test the latest beta builds to see if they fix your issue it would actually be a huge help. I haven't used DTGE before so my tests have been limited to a very basic setup.

Since there's changes to various things in order to make this work, it would also be nice to ensure testing covers usage of prevalue editors (dropdowns, multi value dropdowns, checkbox lists, etc.) used both in normal content + in grid content + in nested content.

I've attached the builds here - if you running the latest versions currently - it should be enough to update the `bin` folder from the Deploy zip - there's no UI changes.

[Umbraco.Deploy.Contrib.0.0.13-alpha.zip](https://github.com/umbraco/Umbraco.Cloud.Issues/files/3719805/Umbraco.Deploy.Contrib.0.0.13-alpha.zip)
[UmbracoDeploy.v2.1.2-beta1.zip](https://github.com/umbraco/Umbraco.Cloud.Issues/files/3719806/UmbracoDeploy.v2.1.2-beta1.zip)

**Comment by jmenendezFKQ** [comment] 2019-10-14 12:51
I will test this today. Thanks for the help :)

**Comment by clausjensen** [comment] 2019-10-15 09:17
No problem - please let us know if you have any trouble - or if it works as intended :)

**Comment by nul800sebastiaan** [comment] 2019-10-21 08:23
@jmenendezFKQ did you have any success with this build?

**Comment by jmenendezFKQ** [comment] 2020-02-13 14:36
Hey clausjensen,

So I finally have enough time to work on this. Sorry for the delay :)

I am having an issue with the Our.Umbraco.DoctypeGridEditor library:

> [ReflectionTypeLoadException: Could not load all types from "Our.Umbraco.DocTypeGridEditor, Version=0.6.6953.20536, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping: System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I am unable to locate that version of System.Web.Http. Did you create this library for version 8 of Umbraco? I am running version 7.15.1.

**Comment by clausjensen** [comment] 2020-02-17 09:32
@jmenendezFKQ Deploy version 2.x is targetted for Umbraco 7 so that should be fine. I'm not really sure why you're getting that error. Do you have any web.config assembly redirects that could be causing problems?

**Comment by FKQEngineering** [comment] 2020-02-19 20:50
Hey clausjensen,

So I misspoke, we are on version 7.14.0 on Umbraco cloud. Here is the error message detail after placing your dlls in our bin:

`[ReflectionTypeLoadException: Could not load all types from "Umbraco.Deploy.Cloud, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
]
   Umbraco.Core.TypeFinder.GetTypesWithFormattedException(Assembly a) +804
   Umbraco.Core.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) +423
   Umbraco.Core.<>c__DisplayClass51_0`1.<ResolveTypes>b__1() +37
   Umbraco.Core.PluginManager.ResolveTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, Boolean cache) +1317
   Umbraco.Core.PluginManager.ResolveTypesInternal(Type baseType, Type attributeType, Func`1 finder, Boolean cache) +218
   Umbraco.Core.PluginManager.ResolveTypes(Boolean cache, IEnumerable`1 specificAssemblies) +353
   Umbraco.Core.CoreBootManager.InitializeApplicationEventsResolver() +71
   Umbraco.Core.CoreBootManager.Initialize() +882
   Umbraco.Web.WebBootManager.Initialize() +19
   Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +266

[HttpException (0x80004005): Could not load all types from "Umbraco.Deploy.Cloud, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +546
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +171
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +255
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +347

[HttpException (0x80004005): Could not load all types from "Umbraco.Deploy.Cloud, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
. System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737`

When I attempt to use Nuget to update those libraries to the versions referenced, the Nuget dependency engine pushes me to upgrade Umbraco to version 7.15.0. Please advise.

**Comment by jmenendezFKQ** [comment] 2020-02-19 21:43
I apologize that is my comment above I was inadvertently signed into a different account when I made the comment

**Comment by nul800sebastiaan** [comment] 2020-08-27 09:52
This has been open for quite a while now, I'll assume that in the mean time this got resolved somehow. I'll close it for now, if you're still running into this we can open it again though! 👍

**Closed by nul800sebastiaan** 2020-08-27 09:52 UTC
Labels: category/umbraco-deploy, state/needs-more-info
