### ISSUE TITLE
Moving datatype into folder doesn't update deploy revision

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#270] opened 2020-10-22 13:17 UTC
When moving datatype instances into a folder, e.g. datatypes based of Nested Content into a folder "Nested Content", it doesn't seem to update the deploy revision files.

However when I afterwards saved the datatype instances it did seem to update the revisions.

Umbraco v8.8.0
Deploy v3.5.1

I have seen this previous, where the environments could come out of sync, because of this mismatch.
Is there someway Deploy could trigger a update in the revision when e.g. a datatype instance is moved into a diffferent folder?

**Comment by ronaldbarendse** [comment] 2021-02-05 10:35
This is related to/a duplicate of https://github.com/umbraco/Umbraco.Cloud.Issues/issues/17.

**Comment by bjarnef** [comment] 2021-02-05 10:47
@ronaldbarendse oh, that's an old bug, but still present 😬🙈

**Comment by nul800sebastiaan** [comment] 2021-03-03 13:01
I'll close this as a duplicate of #17 indeed.

**Closed by nul800sebastiaan** 2021-03-03 13:01 UTC
Labels: category/umbraco-deploy, state/needs-investigation, type/bug
