### ISSUE TITLE
Graphql Caching

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Cloud.Issues#507] opened 2021-12-08 12:58 UTC
### Issue description

Umbraco Heartcore GraphQL is returning a cached response, if you make the exact same request within a specific time period... this isn't really optimal since, we're talking about a CMS system, where users would like to update something in the Backoffice and see the effect immediately on the frontend...

The hacky solution atm:
    const { data, loading, error } = useQuery(fetchFooterMenuLists(), {
      variables: {
        where: {
          NOT: [
            {
              url: Date.now().toString()
            }
          ]
        }
      }
    });

I am adding a useless filter to each request based on the Current time to trick umbraco into thinking it's a new request and returning the correct data.

Is it possible for you to remove the cache or make it a option to remove the cache from umbraco's graphql API?

**Comment by RyuLindow** [comment] 2021-12-08 19:40
Hi @Hanskrogh 

Have you tried to reproduce the same exact query via the GraphQL playground in the backoffice to see if it returns the same result?

GraphQL cache updates automatically after you update content in the backoffice. I've also tested this 2 ish hours after you wrote and it worked fine on my project.

**Comment by Hanskrogh** [comment] 2021-12-08 20:52
Hi @RyuLindow.

Yes I have tried that aswell :( 

If I change the query in any way, we will get a new non-cached result of the query.

I can give an example here:
```
query Footer {
  allFooter {
    items {
      menus {
        name
        __typename
      }
    }
  }
}
```

This would return some data. Now if I go change something in the backoffice, it would return the old cached data...
But if I make any changes to the query, it could be something as simple as swapping around the name and __typename field, umbraco would return the new updated data


```
query Footer {
  allFooter {
    items {
      menus {
        __typename
        name
      }
    }
  }
}
```

My initial thought was that Apollo was returning a cached result, but then I went and tested the same thing in backoffice, the same issue is happening...

**Comment by RyuLindow** [comment] 2021-12-08 20:56
Thanks for getting back and checking this, @Hanskrogh :)

This just might be related to the recent updates the team did to GraphQL.

We'll look into it tomorrow morning :)

**Comment by Hanskrogh** [comment] 2021-12-08 20:59
No Problem @RyuLindow, will you give me and update once you're done looking into it?

I think you're right, been developing on a project for 3 months now, and we just got reported in this issue by a content editor, so it's something that started happening lately! :)

**Comment by RyuLindow** [comment] 2021-12-08 21:01
I'll send you an update by EoD tomorrow :)

**Comment by digitallmn** [comment] 2021-12-09 11:17
We have reported the exact same issue; our theory that responses to previously executed GraphQL queries and cached and served again when an identical query is encountered. This is also a logical and sensible thing, but those cached response should expire within a reasonable time frame and ideally would also be affected by the cache reset buttons that we have in the backoffice. This is something for Umbraco to look at.

**Comment by Hanskrogh** [comment] 2021-12-09 13:28
@digitallmn as @RyuLindow  said the behaviour should be that the caches invalidates on Content Update, to ensure that you're able to see the updates right after content editors have changed something :)

**Comment by RyuLindow** [comment] 2021-12-09 14:49
Hey @Hanskrogh 

That is correct :)

It seems like the caching issue might have appeared after the latest update to GraphQL.

The team will look into it next already next week.

**Comment by RyuLindow** [comment] 2021-12-14 13:14
Hey @Hanskrogh 

The work's in progress. Together with this, we're also looking into the GraphQL issues we had with the platform over the past few weeks.

As for the issue you've mentioned just now, try resaving one of your document/data types to see if that resolves it.

If not, please reach out to support :)

**Comment by Hanskrogh** [comment] 2021-12-14 19:33
Hey @RyuLindow.

Didnt work to save a document/data type....

Support isnt answering us and it is quite urgent that we get the system up and running, since we're going to show the solution to the client tomorrow, do you have any other suggest that might solve the issue? :)

**Comment by sitereactor** [comment] 2021-12-14 19:47
I typically start off by going to Settings / Publishing Status (dashboard) and click rebuild "Database Cache". Once that is done I save all document types and finally do a republish of all Content (on the root node, click Save and Publish with descendents).
This ensures a cache refresh, schema update and then a republish to ensure that content and schema aligns. If, for some reason, a document type was missing as part of the schema, this will ensure that everything is in sync.

All of this is mostly necessary, because the current version of Umbraco Heartcore is pending an update, which fixes these caching issues that stem from the CMS. This update will be rolling out end of December / beginning of January and should eliminate the need for these types of work-arounds.

**Comment by Hanskrogh** [comment] 2021-12-14 19:58
Hi @sitereactor,

Just did what you said and it didn't work...
we still get the error: "Error executing document.", It dosn't matter what we query, all queries return this error :( 

Any other suggestions?

**Comment by sitereactor** [comment] 2021-12-14 20:00
Are you using the GraphQL Playground in the Backoffice? Do you get the Schema tab on the right side and does it have a schema to display/list?
Is the header included in the request?

**Comment by Hanskrogh** [comment] 2021-12-14 20:03
Yes, I am.

Once we do the request we get the Schema tab, but if we open it, it just keeps loading no result...

request headers:

![Headers](https://user-images.githubusercontent.com/43749842/146071097-97a986f9-9e58-4d50-9acf-64ecd0340e6f.PNG)

**Comment by Hanskrogh** [comment] 2021-12-14 20:05
Here's an image of how the request looks like:
![image](https://user-images.githubusercontent.com/43749842/146071370-3a0fe568-3987-49d5-9b4c-f2b7bee28bb8.png)

**Comment by sitereactor** [comment] 2021-12-14 20:29
Something in the schema must be broken. The schema tab should be loading the schema from the GraphQL API, so something is not quite right.
Do you have the same doc types, data types, etc. on the Development environment where its working?

**Comment by Hanskrogh** [comment] 2021-12-14 20:31
Nope, we do not have a development environment, tried to create one earlier but i didnt work,

I get the folllowing error, when trying to create a development environment, it complains about we have Two Media pickers, which is odd, because Media Picker is a default data type...

![image](https://user-images.githubusercontent.com/43749842/146074862-e71be83a-402a-42ef-95e5-bf03ca2d524c.png)

**Comment by sitereactor** [comment] 2021-12-14 21:12
The data types is part of what caused the Development environment to not work (it was unable to extract the doc types, data types, etc.).
The default Media Picker was deleted and then a new Media Picker was created and used in various doc types. Because the name is the same there will be a collision on the data type, because Umbraco creates one by default.
I think you can rename the data type in the Live environment and then when you create a new Development environment there should not be a collision on the name.

**Comment by Hanskrogh** [comment] 2021-12-14 21:16
Sounds good! :) 

What about the graphql, did you manage to figure out the issue about the schema?

**Comment by sitereactor** [comment] 2021-12-14 21:23
No, I haven't pinpointed the exact issue, but its most likely related to the doc types, data types and the schema it creates. Right now it appears as though something is corrupt in the schema.
Will need to dig further into some logs from the GraphQL server tomorrow. But cleaning out unused data types and ensuring that the various doc types / element types / nested content doesn't reference something that no longer exists would be s good start.

**Comment by Hanskrogh** [comment] 2021-12-14 21:36
Is there a way to copy all content from live to developer environment? the Graphql is working on development environment now, but our content didn't get transfered.

**Comment by vukovinski** [comment] 2021-12-15 10:18
We also have a similar issue, at least with the GraphQL playground.

**Comment by miguelcrpinto** [comment] 2021-12-15 11:15
We are having a similar issue. I'm still investigating but it seems that the issue was on a composition document type. As soon as I removed all the compositions from the content document types, the graphql schema was available again.

**Comment by miguelcrpinto** [comment] 2021-12-15 13:18
it seems that the issue was indeed that our compositions were marked as element types.

@sitereactor why is this an issue in one of my heartcore projects but not on another one? on the other project I have the compositions marked as element types and I'm able to browse the graphql schema and query for documents.

**Comment by Hanskrogh** [comment] 2021-12-15 14:21
@miguelcrpinto This is true, we had a composition as element type aswell, once it was moved, it fixed our error!!

**Comment by sitereactor** [comment] 2021-12-15 14:58
@miguelcrpinto the best answer I can give currently is that
1. An Element Type can be used as a Composition on another Element Type
2. An Element Type cannot be used as a Composition on a Document Type

This might be slightly confusing, and maybe more so, as there are no guardrails in the CMS, which helps enforce this. But its these rules that are used when building the GraphQL Schema

**Comment by miguelcrpinto** [comment] 2021-12-15 15:09
Ignore my previous comment about the other project. I do have compositions as element types but they are being used by other element types and not by actual pages. The compositions I use in the actual pages **are not** element types .

@sitereactor might be a good idea to document this somewhere

**Comment by sitereactor** [comment] 2021-12-15 15:11
yes, agree. Ideally we'd have it enforce in the CMS as well, so you can't get yourself into trouble.

**Comment by anthwinter** [comment] 2021-12-21 10:26
We are seeing caching happening on our Umbraco Heartcore projects too.

When updating a content page, saving and publishing it, and then going to the GraphQL Playground to query the result, it shows the old data.

**Comment by sitereactor** [comment] 2022-01-11 08:41
Sorry for the delay in getting back to this thread.
We have been working on improving the caching issues that was highlighted in this thread and which we could also reproduce ourselves.

We did two updates during December, which didn't have the desired improvement, so we reworked our cache refresh strategy to be more reliable than previously. We have seen positive effects of this change, and we believe it should no longer be necessary to circumvent the caching by sending unique parameters with every request (like DateTime.Now).
Queries will be served from the cache until new Content is published or until metadata is changed (doc types, data types, etc). So cache is invalidated as you would expect.

There is currently a small delay in refreshing the cache, which vary depending on edge locations (ie. Europe will update faster than Australia). We continue to do work on improving the time it takes to refresh the cache, but the cache invalidation and refresh is working as expected now so will close this issue.

Please let us know if you feel like you are still experiencing issues related to caching of GraphQL queries. Happy to revisit if necessary.

**Closed by sitereactor** 2022-01-11 08:41 UTC
Labels: category/heartcore
