### ISSUE TITLE
Update baseline children progress not showing

### ISSUE THREAD

**Issue by orsinic** [umbraco/Umbraco.Cloud.Issues#99] opened 2019-07-30 15:24 UTC
Trying to update child projects in an Umbraco Cloud baseline setup works, but the progress doesn't show as expected.
 
Reproduction steps: 
- go to https://www.s1.umbraco.io/project/[baselineproject]/managebaselinechildren
- select one or more child projects (works)
- confirm button appears (works)
- click confirm button: **nothing seems to happen, progress not displayed**

The selected child projects are however updated when checking them after a while. It's just the renewed progress interface that blocks.

A second or two after confirming a javascript error is thrown:

app.js?v=637000686800000000:3 TypeError: Cannot set property 'updating' of undefined
    at app.js?v=637000686800000000:12
    at f.$eval (app.js?v=637000686800000000:3)
    at f.$apply (app.js?v=637000686800000000:3)
    at app.js?v=637000686800000000:12
    at f.$broadcast (app.js?v=637000686800000000:3)
    at init.n.client.updateStatus (app.js?v=637000686800000000:13)
    at init.<anonymous> (hubs:26)
    at init.r.<computed>.<computed> (jquery.signalR-1.1.4.min.js:10)
    at init.dispatch (jquery-2.1.4.min.js:3)
    at init.r.handle (jquery-2.1.4.min.js:3)

Using Chrome (also tried incognito with cleared browser cache etc).

Expected result: see the progress of each child in the red/green sections on the page.

![image](https://user-images.githubusercontent.com/6575349/62142447-ab745800-b2ee-11e9-888d-c9ffc288b702.png)

**Comment by nul800sebastiaan** [comment] 2020-02-18 13:43
Hey @orsinic - sorry for the late reply, we tried reproducing this but it looks like this is probably fixed by now. Let us know if you can still reproduce this and what steps we need to take for that! 👍

**Closed by nul800sebastiaan** 2020-02-18 13:43 UTC

**Comment by reneemhaas** [comment] 2020-03-23 21:50
This is still an issue for me and has been for many months.
