### ISSUE TITLE
Dictionary items are not re-saved after deleting a backoffice language, which may result in an extraction error

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#209] opened 2020-05-19 12:47 UTC
Defining dictionary items in the backoffice, and then removing one of the languages may cause some issues when creating a new environment/baseline child.

Reproduction
------------

### Specifics

Seems to apply to all v8 versions - I tested on 8.6.1

### Steps to reproduce

1. Spin up a new project on Cloud
2. Add some languages to the backoffice
3. Define dictionary items, save some values in different languages
4. Delete one of the backoffice languages via the Settings menu
5. Spin up a new Development environment, or create a child project based on the project with the dictionary items

### Expected result

The new environment/project is good to go and has no issues.

### Actual result

Extraction error - 'Languages in source and destination site do not match'
![error](https://user-images.githubusercontent.com/56038614/82327842-4a358680-99df-11ea-94d1-7f851c7dadf1.png)
![detailed-error](https://user-images.githubusercontent.com/56038614/82327848-4bff4a00-99df-11ea-8a06-b3f6c359f8a2.png)

Workarounds
------------
I wrote an article on troubleshooting this issue, though it would be great to get it fixed in the CMS itself. Due to the nature of this bug, it might also qualify for the CMS issue tracker.

The simple workaround - resave the dictionary items manually on source env and re-create the other environment/project.
The complex workaround - manually remove the missing language section from the UDA file directly on the new environment via KUDU tools and run a manual extraction.
![kudutools](https://user-images.githubusercontent.com/56038614/82328037-9f719800-99df-11ea-95c6-99749b2977a9.png)

**Comment by nul800sebastiaan** [comment] 2020-05-19 13:43
Sorry to immediately close this again after such a nice lengthy report, but for the same reason as mentioned in #207 - we do not deal with deletions at the moment so that we don't accidentally delete things we shouldn't. It's a huge topic for the future, but we're not ready to work on that at this time.

**Closed by nul800sebastiaan** 2020-05-19 13:43 UTC

**Comment by ronaldbarendse** [comment] 2020-08-21 08:04
@Jay-umbr Instead of manually re-saving all dictionary items, you can also run a full deploy export by adding the `data\deploy-export` marker file.

@nul800sebastiaan The problem isn't with Deploy not deleting things, it's Deploy not updating the relevant metadata/UDA files, so they become inconsistent. When removing a language locally (from the back-office), all dictionary items are also deleted from the database. If you want to remove the language in another environment, you need to do the same (as expected).

The problem occurs when the language isn't available (e.g. because it's manually deleted or it's a new local restore), but the dictionary item metadata/UDA files still contain translations for a non-existent language. Deploy tries to restore the translation for this language, but throws an error, because the language doesn't exist!

This is slightly related to issue https://github.com/umbraco/Umbraco.Cloud.Issues/issues/188.
